Update ChatTTS template

diff --git a/examples/ai/ecs-instance-chat-tts.yml b/examples/ai/ecs-instance-chat-tts.yml
--- a/examples/ai/ecs-instance-chat-tts.yml
+++ b/examples/ai/ecs-instance-chat-tts.yml
@@ -124,9 +124,16 @@ Resources:
         echo "#########################"
         echo "# Install ChatTTS Web UI"
         echo "#########################"
-        apt update
-        apt install -y python3-venv
-        git config --global http.version HTTP/1.1 && git clone --depth 1 https://github.com/jianchang512/ChatTTS-ui.git /opt/chat-tts-ui && cd /opt/chat-tts-ui
+        apt-get update
+        apt-get install -y python3-venv
+        
+        git clone --depth 1 https://gitclone.com/github.com/jianchang512/ChatTTS-ui.git /opt/chat-tts-ui && cd /opt/chat-tts-ui
+        ret_code=$?
+        if [ $ret_code -ne 0 ]; then
+          echo "Git clone https://gitclone.com/github.com/jianchang512/ChatTTS-ui.git failed. Exiting."
+          exit $ret_code
+        fi
+        
         python3 -m venv venv
         source ./venv/bin/activate
         pip3 install -r requirements.txt
