Added whether to select an existing instance parameter

diff --git a/examples/elastic/lnmp-basic.yml b/examples/elastic/lnmp-basic.yml
--- a/examples/elastic/lnmp-basic.yml
+++ b/examples/elastic/lnmp-basic.yml
@@ -4,6 +4,15 @@ Description:
     Only support CentOS-7.
   zh-cn: 在1个ECS实例上部署 LNMP（Linux+Nginx+MySQL+PHP）堆栈；模板仅支持 CentOS-7。
 Parameters:
+  SelectExistECS:
+    Type: Boolean
+    Label:
+      en: Whether to select an existing instance
+      zh-cn: 是否选择已有实例
+    Description:
+      en: Whether to select an existing Centos7 system instance. The Centos7 system instance must be connected to a public network.
+      zh-cn: 是否选择已有Centos7系统实例，实例需要开通公网。
+    Default: false
   ZoneId:
     Type: String
     Label:
@@ -15,17 +24,31 @@ Parameters:
         ECS resources</font></b>
       zh-cn: 可用区ID。<br><b>注： <font color='blue'>选择可用区前请确认该可用区是否支持创建ECS资源的规格</font></b>
     AssociationProperty: ALIYUN::ECS::Instance::ZoneId
-  ImageId:
+    AssociationPropertyMetadata:
+      ZoneId: ZoneId
+      Visible:
+        Condition:
+          Fn::Equals:
+            - ${SelectExistECS}
+            - false
+    Default: null
+  ECSInstanceId:
     Type: String
     Label:
-      en: Image ID
-      zh-cn: 镜像ID
+      en: Existing ECS Instance
+      zh-cn: 已创建ECS实例
     Description:
-      en: 'Server instance Image ID. see detail: <b><a href=''https://www.alibabacloud.com/help/doc-detail/112977.html''
-        target=''_blank''><font color=''blue''>Find the mirror</font></a></b>'
-      zh-cn: 服务器镜像，详见：<b><a href='https://help.aliyun.com/document_detail/112977.html'
-        target='_blank'><font color='blue'>查找镜像</font></a></b>
-    Default: centos_7
+      en: Select an ECS instance with the CentOS 7.9 64-bit operating system. 
+      zh-cn: 选择已存在操作系统为CentOS 7.9 64位的ECS实例。
+    AssociationProperty: ALIYUN::ECS::Instance::InstanceId
+    AssociationPropertyMetadata:
+      ZoneId: ZoneId
+      Visible:
+        Condition:
+          Fn::Equals:
+            - ${SelectExistECS}
+            - true
+    Default: null
   InstanceType:
     Type: String
     Label:
@@ -42,6 +65,12 @@ Parameters:
     AssociationProperty: ALIYUN::ECS::Instance::InstanceType
     AssociationPropertyMetadata:
       ZoneId: ZoneId
+      Visible:
+        Condition:
+          Fn::Equals:
+            - ${SelectExistECS}
+            - false
+    Default: ecs.c5.large
   SystemDiskCategory:
     Type: String
     Label:
@@ -57,13 +86,16 @@ Parameters:
         color=''green''>高效云盘</font>]<br>[cloud_ssd: <font color=''green''>SSD云盘</font>]<br>[cloud_essd:
         <font color=''green''>ESSD云盘</font>]<br>[cloud: <font color=''green''>普通云盘</font>]<br>[ephemeral_ssd:
         <font color=''green''>本地SSD盘</font>]'
-    Default: cloud_ssd
-    AllowedValues:
-    - cloud_efficiency
-    - cloud_ssd
-    - cloud
-    - cloud_essd
-    - ephemeral_ssd
+    AssociationPropertyMetadata:
+      LocaleKey: DiskCategory
+      InstanceType: ${InstanceType}
+      ZoneId: ZoneId
+      Visible:
+        Condition:
+          Fn::Equals:
+            - ${SelectExistECS}
+            - false
+    Default: cloud_efficiency
   InstancePassword:
     Type: String
     Label:
@@ -78,9 +110,16 @@ Parameters:
         special symbols three; special characters include: ()`~!@#$%^&*_-+=|{}[]:;''<>,.?/'
       zh-cn: 长度8-30，必须包含大写字母、小写字母、数字、特殊符号三种；特殊字符包括：()`~!@#$%^&*_-+=|{}[]:;' <>,.?/
     AllowedPattern: '[0-9A-Za-z\_\-&:;''<>,=%`~!@#\(\)\$\^\*\+\|\{\}\[\]\.\?\/]+$'
+    AssociationPropertyMetadata:
+      Visible:
+        Condition:
+          Fn::Equals:
+            - ${SelectExistECS}
+            - false
     MinLength: '8'
     MaxLength: '30'
     NoEcho: true
+    Default: null
   DBName:
     Type: String
     Label:
@@ -153,9 +192,19 @@ Parameters:
       en: nginx-.rpm source download path.
       zh-cn: nginx-*.rpm源下载路径
     Default: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
+Conditions:
+  IsSelectExistECS:
+    Fn::Equals:
+      - Ref: SelectExistECS
+      - false
+  NotSelectExistECS:
+    Fn::Equals:
+      - Ref: SelectExistECS
+      - true
 Resources:
   EcsVpc:
     Type: ALIYUN::ECS::VPC
+    Condition: IsSelectExistECS
     Properties:
       CidrBlock: 192.168.0.0/16
     Metadata:
@@ -163,6 +212,7 @@ Resources:
         id: 598ced8b-0ba4-40a8-a781-1d48e26ca15f
   EcsSecurityGroup:
     Type: ALIYUN::ECS::SecurityGroup
+    Condition: IsSelectExistECS
     Properties:
       VpcId:
         Ref: EcsVpc
@@ -183,6 +233,7 @@ Resources:
         id: 7a621d9a-c803-4121-ba09-30dc9a417423
   EcsVSwitch:
     Type: ALIYUN::ECS::VSwitch
+    Condition: IsSelectExistECS
     Properties:
       ZoneId:
         Ref: ZoneId
@@ -194,6 +245,7 @@ Resources:
         id: dae2dd74-1b30-4975-8b70-4877f4c2d9d3
   WebServer:
     Type: ALIYUN::ECS::Instance
+    Condition: IsSelectExistECS
     Properties:
       VpcId:
         Fn::GetAtt:
@@ -203,8 +255,7 @@ Resources:
         Ref: EcsVSwitch
       SecurityGroupId:
         Ref: EcsSecurityGroup
-      ImageId:
-        Ref: ImageId
+      ImageId: centos_7
       InstanceType:
         Ref: InstanceType
       InternetMaxBandwidthOut: 80
@@ -213,101 +264,107 @@ Resources:
         Ref: InstancePassword
       SystemDiskCategory:
         Ref: SystemDiskCategory
-      UserData:
-        Fn::Replace:
-        - ros-notify:
-            Fn::GetAtt:
-            - WebServerConditionHandle
-            - CurlCli
-        - Fn::Join:
-          - ''
-          - - "#!/bin/bash \n"
-            - NginxUrl=
-            - Ref: NginxDownloadUrl
-            - '
-
-              '
-            - dbname=
-            - Ref: DBName
-            - '
-
-              '
-            - dbuser=
-            - Ref: DBUser
-            - '
-
-              '
-            - dbpassword=
-            - Ref: DBPassword
-            - '
-
-              '
-            - dbrootpassword=
-            - Ref: DBRootPassword
-            - '
-
-              '
-            - "export HOME=/root \n"
-            - "export HOSTNAME=`hostname` \n"
-            - "systemctl stop firewalld.service \n"
-            - "systemctl disable firewalld.service \n"
-            - "sed -i 's/^SELINUX=/# SELINUX=/' /etc/selinux/config \n"
-            - "sed -i '/# SELINUX=/a SELINUX=disabled' /etc/selinux/config \n"
-            - "setenforce 0 \n"
-            - "yum install yum-priorities -y \n"
-            - "yum -y install aria2 \n"
-            - "aria2c $NginxUrl \n"
-            - "rpm -ivh nginx-*.rpm \n"
-            - "yum -y install nginx \n"
-            - "systemctl start nginx.service \n"
-            - "systemctl enable nginx.service \n"
-            - "yum -y install php-fpm \n"
-            - "systemctl start php-fpm.service \n"
-            - "systemctl enable php-fpm.service \n"
-            - "sed -i '/FastCGI/,/htaccess/s/    #/    /' /etc/nginx/conf.d/default.conf\
-              \ \n"
-            - "sed -i '/FastCGI/s/^    /    #/' /etc/nginx/conf.d/default.conf \n"
-            - "sed -i '/htaccess/s/^    /    #/' /etc/nginx/conf.d/default.conf \n"
-            - "sed -i '/SCRIPT_FILENAME/s/\\/scripts/\\/usr\\/share\\/nginx\\/html\\\
-              //' /etc/nginx/conf.d/default.conf \n"
-            - "yum -y install mariadb mariadb-server \n"
-            - "systemctl start mariadb.service \n"
-            - "systemctl enable mariadb.service \n"
-            - "yum -y install php php-mysql php-gd libjpeg* php-ldap php-odbc php-pear\
-              \ php-xml php-xmlrpc php-mbstring php-bcmath php-mhash php-mcrypt \n"
-            - "MDSRING=`find / -name mbstring.so` \n"
-            - "echo extension=$MDSRING >> /etc/php.ini \n"
-            - "systemctl restart mariadb.service \n"
-            - "mysqladmin -u root password \"$dbrootpassword\" \n"
-            - "$(mysql $dbname -u root --password=\"$dbrootpassword\" >/dev/null 2>&1\
-              \ </dev/null); (( $? != 0 )) \n"
-            - "echo CREATE DATABASE $dbname \\; > /tmp/setup.mysql \n"
-            - "echo GRANT ALL ON $dbname.* TO \"$dbuser\"@\"localhost\" IDENTIFIED\
-              \ BY \"'$dbpassword'\" \\; >> /tmp/setup.mysql \n"
-            - "mysql -u root --password=\"$dbrootpassword\" < /tmp/setup.mysql \n"
-            - "$(mysql $dbname -u root --password=\"$dbrootpassword\" >/dev/null 2>&1\
-              \ </dev/null); (( $? != 0 )) \n"
-            - "cd /root \n"
-            - "systemctl restart php-fpm.service \n"
-            - "systemctl restart nginx.service \n"
-            - "echo \\<?php >  /usr/share/nginx/html/test.php \n"
-            - "echo \\$conn=mysql_connect\\(\"'127.0.0.1'\", \"'$dbuser'\", \"'$dbpassword'\"\
-              \\)\\; >>  /usr/share/nginx/html/test.php \n"
-            - "echo if \\(\\$conn\\){ >>  /usr/share/nginx/html/test.php \n"
-            - "echo   echo \\\"LNMP platform connect to mysql is successful\\!\\\"\
-              \\; >>  /usr/share/nginx/html/test.php \n"
-            - "echo   }else{  >>  /usr/share/nginx/html/test.php \n"
-            - "echo echo \\\"LNMP platform connect to mysql is failed\\!\\\"\\;  >>\
-              \  /usr/share/nginx/html/test.php \n"
-            - "echo }  >>  /usr/share/nginx/html/test.php \n"
-            - "echo  phpinfo\\(\\)\\;  >>  /usr/share/nginx/html/test.php \n"
-            - "echo \\?\\>  >>  /usr/share/nginx/html/test.php \n"
-            - 'ros-notify -d ''{"data" : "Install LNMP stack."}''
-
-              '
     Metadata:
       ALIYUN::ROS::Designer:
         id: 0af5b81e-0e55-4e6a-ba96-45cf7a730510
+  ExistWebServer:
+    Type: DATASOURCE::ECS::Instances
+    Condition: NotSelectExistECS
+    Properties:
+      InstanceId:
+        Ref: ECSInstanceId
+  Command:
+    Type: ALIYUN::ECS::Command
+    Properties:
+      Timeout: 1800
+      CommandContent:
+        Fn::Base64Encode:
+          Fn::Sub:
+            - |-
+              #!/bin/bash
+              NginxUrl=${NginxUrl}
+              dbname=${DBName}
+              dbuser=${DBUser}
+              dbpassword=${DBPassword}
+              dbrootpassword=${DBRootPassword}
+              export HOME=/root
+              export HOSTNAME=`hostname`
+              systemctl stop firewalld.service
+              systemctl disable firewalld.service
+              sed -i 's/^SELINUX=/# SELINUX=/' /etc/selinux/config 
+              sed -i '/# SELINUX=/a SELINUX=disabled' /etc/selinux/config 
+              setenforce 0 
+              yum install yum-priorities -y
+              yum -y install aria2
+              aria2c $NginxUrl
+              rpm -ivh nginx-*.rpm
+              yum -y install nginx
+              systemctl start nginx.service
+              systemctl enable nginx.service
+              yum -y install php-fpm
+              systemctl start php-fpm.service
+              systemctl enable php-fpm.service
+              sed -i '/FastCGI/,/htaccess/s/    #/    /' /etc/nginx/conf.d/default.conf 
+              sed -i '/FastCGI/s/^    /    #/' /etc/nginx/conf.d/default.conf 
+              sed -i '/htaccess/s/^    /    #/' /etc/nginx/conf.d/default.conf 
+              sed -i '/SCRIPT_FILENAME/s/\/scripts/\/usr\/share\/nginx\/html\//' /etc/nginx/conf.d/default.conf
+              yum -y install mariadb mariadb-server 
+              systemctl start mariadb.service 
+              systemctl enable mariadb.service 
+              yum -y install php php-mysql php-gd libjpeg* php-ldap php-odbc php-pear php-xml php-xmlrpc php-mbstring php-bcmath php-mhash php-mcrypt 
+              MDSRING=`find / -name mbstring.so` 
+              echo extension=$MDSRING >> /etc/php.ini 
+              systemctl restart mariadb.service 
+              mysqladmin -u root password "$dbrootpassword" 
+              $(mysql $dbname -u root --password="$dbrootpassword" >/dev/null 2>&1 </dev/null); (( $? != 0 )) 
+              echo CREATE DATABASE $dbname \; > /tmp/setup.mysql 
+              echo GRANT ALL ON $dbname.* TO "$dbuser"@"localhost" IDENTIFIED BY "'$dbpassword'" \; >> /tmp/setup.mysql 
+              mysql -u root --password="$dbrootpassword" < /tmp/setup.mysql 
+              $(mysql $dbname -u root --password="$dbrootpassword" >/dev/null 2>&1 </dev/null); (( $? != 0 )) 
+              cd /root 
+              systemctl restart php-fpm.service 
+              systemctl restart nginx.service 
+              echo \<?php >  /usr/share/nginx/html/test.php 
+              echo \$conn=mysql_connect\("'127.0.0.1'", "'$dbuser'", "'$dbpassword'"\)\; >>  /usr/share/nginx/html/test.php 
+              echo if \(\$conn\){ >>  /usr/share/nginx/html/test.php 
+              echo   echo \"LNMP platform connect to mysql is successful\!\"\; >>  /usr/share/nginx/html/test.php 
+              echo   }else{  >>  /usr/share/nginx/html/test.php 
+              echo echo \"LNMP platform connect to mysql is failed\!\"\;  >>  /usr/share/nginx/html/test.php 
+              echo }  >>  /usr/share/nginx/html/test.php 
+              echo  phpinfo\(\)\;  >>  /usr/share/nginx/html/test.php 
+              echo \?\>  >>  /usr/share/nginx/html/test.php
+              ${CurlCli} -d '{"data" : "Install nginx."}'
+            - NginxUrl:
+                Ref: NginxDownloadUrl
+              DBName:
+                Ref: DBName
+              DBUser:
+                Ref: DBUser
+              DBPassword:
+                Ref: DBPassword
+              DBRootPassword:
+                Ref: DBRootPassword
+              CurlCli:
+                Fn::GetAtt:
+                  - WebServerConditionHandle
+                  - CurlCli
+      Type: RunShellScript
+      Name:
+        Ref: ALIYUN::StackId
+    DependsOn:
+      - WebServerConditionHandle
+  Invocation:
+    Type: ALIYUN::ECS::Invocation
+    Properties:
+      InstanceIds:
+        - Fn::If:
+            - IsSelectExistECS
+            - Fn::GetAtt:
+                - WebServer
+                - InstanceId
+            - Ref: ECSInstanceId
+      CommandId:
+        Ref: Command
   WebServerConditionHandle:
     Type: ALIYUN::ROS::WaitConditionHandle
     Properties: {}
@@ -329,19 +386,29 @@ Outputs:
   NginxWebsiteURL:
     Description: URL for newly created Nginx home page.
     Value:
-      Fn::Join:
-      - ''
-      - - http://
-        - Fn::GetAtt:
-          - WebServer
-          - PublicIp
-        - :80/test.php
+      Fn::Sub:
+        - 'http://${IP}:80/test.php'
+        - IP:
+            'Fn::If':
+              - IsSelectExistECS
+              - 'Fn::GetAtt':
+                  - WebServer
+                  - PublicIp
+              - 'Fn::Jq':
+                  - First
+                  - >-
+                    if .[0].PublicIpAddress != [] then .[0].PublicIpAddress[0]
+                    else .[0].EipAddress.IpAddress end
+                  - 'Fn::GetAtt':
+                      - ExistWebServer
+                      - Instances
 Metadata:
   ALIYUN::ROS::Interface:
     ParameterGroups:
     - Parameters:
+      - SelectExistECS
       - ZoneId
-      - ImageId
+      - ECSInstanceId
       - InstanceType
       - SystemDiskCategory
       - InstancePassword
