fix lnmp-basic.yml duplicate keys

diff --git a/examples/elastic/lnmp-basic.yml b/examples/elastic/lnmp-basic.yml
--- a/examples/elastic/lnmp-basic.yml
+++ b/examples/elastic/lnmp-basic.yml
@@ -19,7 +19,8 @@ Parameters:
       en: Whether to select an existing instance
       zh-cn: 是否选择已有实例
     Description:
-      en: Whether to select an existing Centos7 system instance. The Centos7 system instance must be connected to a public network.
+      en: Whether to select an existing Centos7 system instance. The Centos7 system
+        instance must be connected to a public network.
       zh-cn: 是否选择已有Centos7系统实例，实例需要开通公网。
     Default: false
   ZoneId:
@@ -38,8 +39,8 @@ Parameters:
       Visible:
         Condition:
           Fn::Equals:
-            - ${SelectExistECS}
-            - false
+          - ${SelectExistECS}
+          - false
     Default: null
   ECSInstanceId:
     Type: String
@@ -47,7 +48,7 @@ Parameters:
       en: Existing ECS Instance
       zh-cn: 已创建ECS实例
     Description:
-      en: Select an ECS instance with the CentOS 7.9 64-bit operating system. 
+      en: Select an ECS instance with the CentOS 7.9 64-bit operating system.
       zh-cn: 选择已存在操作系统为CentOS 7.9 64位的ECS实例。
     AssociationProperty: ALIYUN::ECS::Instance::InstanceId
     AssociationPropertyMetadata:
@@ -55,8 +56,8 @@ Parameters:
       Visible:
         Condition:
           Fn::Equals:
-            - ${SelectExistECS}
-            - true
+          - ${SelectExistECS}
+          - true
     Default: null
   InstanceType:
     Type: String
@@ -77,8 +78,8 @@ Parameters:
       Visible:
         Condition:
           Fn::Equals:
-            - ${SelectExistECS}
-            - false
+          - ${SelectExistECS}
+          - false
     Default: ecs.c5.large
   SystemDiskCategory:
     Type: String
@@ -93,8 +94,8 @@ Parameters:
       Visible:
         Condition:
           Fn::Equals:
-            - ${SelectExistECS}
-            - false
+          - ${SelectExistECS}
+          - false
     Default: cloud_efficiency
   InstancePassword:
     Type: String
@@ -109,17 +110,17 @@ Parameters:
       en: 'Length 8-30, must contain upper case letters, lower case letters, Numbers,
         special symbols three; special characters include: ()`~!@#$%^&*_-+=|{}[]:;''<>,.?/'
       zh-cn: 长度8-30，必须包含大写字母、小写字母、数字、特殊符号三种；特殊字符包括：()`~!@#$%^&*_-+=|{}[]:;' <>,.?/
-    AllowedPattern: '[0-9A-Za-z\_\-&:;''<>,=%`~!@#\(\)\$\^\*\+\|\{\}\[\]\.\?\/]+$'
     AssociationPropertyMetadata:
       Visible:
         Condition:
           Fn::Equals:
-            - ${SelectExistECS}
-            - false
+          - ${SelectExistECS}
+          - false
+    Default: null
+    AllowedPattern: '[0-9A-Za-z\_\-&:;''<>,=%`~!@#\(\)\$\^\*\+\|\{\}\[\]\.\?\/]+$'
     MinLength: '8'
     MaxLength: '30'
     NoEcho: true
-    Default: null
   DBName:
     Type: String
     Label:
@@ -191,16 +192,8 @@ Parameters:
     Description:
       en: nginx-.rpm source download path.
       zh-cn: nginx-*.rpm源下载路径
-    Default: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
-Conditions:
-  IsSelectExistECS:
-    Fn::Equals:
-      - Ref: SelectExistECS
-      - false
-  NotSelectExistECS:
-    Fn::Equals:
-      - Ref: SelectExistECS
-      - true
+    Default: 
+      http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
 Resources:
   EcsVpc:
     Type: ALIYUN::ECS::VPC
@@ -273,6 +266,12 @@ Resources:
     Properties:
       InstanceId:
         Ref: ECSInstanceId
+  WebServerConditionHandle:
+    Type: ALIYUN::ROS::WaitConditionHandle
+    Properties: {}
+    Metadata:
+      ALIYUN::ROS::Designer:
+        id: ec1625d7-b79b-496d-ba3a-5c46be0c1181
   Command:
     Type: ALIYUN::ECS::Command
     Properties:
@@ -280,97 +279,91 @@ Resources:
       CommandContent:
         Fn::Base64Encode:
           Fn::Sub:
-            - |-
-              #!/bin/bash
-              NginxUrl=${NginxUrl}
-              dbname=${DBName}
-              dbuser=${DBUser}
-              dbpassword=${DBPassword}
-              dbrootpassword=${DBRootPassword}
-              export HOME=/root
-              export HOSTNAME=`hostname`
-              systemctl stop firewalld.service
-              systemctl disable firewalld.service
-              sed -i 's/^SELINUX=/# SELINUX=/' /etc/selinux/config 
-              sed -i '/# SELINUX=/a SELINUX=disabled' /etc/selinux/config 
-              setenforce 0 
-              yum install yum-priorities -y
-              yum -y install aria2
-              aria2c $NginxUrl
-              rpm -ivh nginx-*.rpm
-              yum -y install nginx
-              systemctl start nginx.service
-              systemctl enable nginx.service
-              yum -y install php-fpm
-              systemctl start php-fpm.service
-              systemctl enable php-fpm.service
-              sed -i '/FastCGI/,/htaccess/s/    #/    /' /etc/nginx/conf.d/default.conf 
-              sed -i '/FastCGI/s/^    /    #/' /etc/nginx/conf.d/default.conf 
-              sed -i '/htaccess/s/^    /    #/' /etc/nginx/conf.d/default.conf 
-              sed -i '/SCRIPT_FILENAME/s/\/scripts/\/usr\/share\/nginx\/html\//' /etc/nginx/conf.d/default.conf
-              yum -y install mariadb mariadb-server 
-              systemctl start mariadb.service 
-              systemctl enable mariadb.service 
-              yum -y install php php-mysql php-gd libjpeg* php-ldap php-odbc php-pear php-xml php-xmlrpc php-mbstring php-bcmath php-mhash php-mcrypt 
-              MDSRING=`find / -name mbstring.so` 
-              echo extension=$MDSRING >> /etc/php.ini 
-              systemctl restart mariadb.service 
-              mysqladmin -u root password "$dbrootpassword" 
-              $(mysql $dbname -u root --password="$dbrootpassword" >/dev/null 2>&1 </dev/null); (( $? != 0 )) 
-              echo CREATE DATABASE $dbname \; > /tmp/setup.mysql 
-              echo GRANT ALL ON $dbname.* TO "$dbuser"@"localhost" IDENTIFIED BY "'$dbpassword'" \; >> /tmp/setup.mysql 
-              mysql -u root --password="$dbrootpassword" < /tmp/setup.mysql 
-              $(mysql $dbname -u root --password="$dbrootpassword" >/dev/null 2>&1 </dev/null); (( $? != 0 )) 
-              cd /root 
-              systemctl restart php-fpm.service 
-              systemctl restart nginx.service 
-              echo \<?php >  /usr/share/nginx/html/test.php 
-              echo \$conn=mysql_connect\("'127.0.0.1'", "'$dbuser'", "'$dbpassword'"\)\; >>  /usr/share/nginx/html/test.php 
-              echo if \(\$conn\){ >>  /usr/share/nginx/html/test.php 
-              echo   echo \"LNMP platform connect to mysql is successful\!\"\; >>  /usr/share/nginx/html/test.php 
-              echo   }else{  >>  /usr/share/nginx/html/test.php 
-              echo echo \"LNMP platform connect to mysql is failed\!\"\;  >>  /usr/share/nginx/html/test.php 
-              echo }  >>  /usr/share/nginx/html/test.php 
-              echo  phpinfo\(\)\;  >>  /usr/share/nginx/html/test.php 
-              echo \?\>  >>  /usr/share/nginx/html/test.php
-              ${CurlCli} -d '{"data" : "Install nginx."}'
-            - NginxUrl:
-                Ref: NginxDownloadUrl
-              DBName:
-                Ref: DBName
-              DBUser:
-                Ref: DBUser
-              DBPassword:
-                Ref: DBPassword
-              DBRootPassword:
-                Ref: DBRootPassword
-              CurlCli:
-                Fn::GetAtt:
-                  - WebServerConditionHandle
-                  - CurlCli
+          - |-
+            #!/bin/bash
+            NginxUrl=${NginxUrl}
+            dbname=${DBName}
+            dbuser=${DBUser}
+            dbpassword=${DBPassword}
+            dbrootpassword=${DBRootPassword}
+            export HOME=/root
+            export HOSTNAME=`hostname`
+            systemctl stop firewalld.service
+            systemctl disable firewalld.service
+            sed -i 's/^SELINUX=/# SELINUX=/' /etc/selinux/config 
+            sed -i '/# SELINUX=/a SELINUX=disabled' /etc/selinux/config 
+            setenforce 0 
+            yum install yum-priorities -y
+            yum -y install aria2
+            aria2c $NginxUrl
+            rpm -ivh nginx-*.rpm
+            yum -y install nginx
+            systemctl start nginx.service
+            systemctl enable nginx.service
+            yum -y install php-fpm
+            systemctl start php-fpm.service
+            systemctl enable php-fpm.service
+            sed -i '/FastCGI/,/htaccess/s/    #/    /' /etc/nginx/conf.d/default.conf 
+            sed -i '/FastCGI/s/^    /    #/' /etc/nginx/conf.d/default.conf 
+            sed -i '/htaccess/s/^    /    #/' /etc/nginx/conf.d/default.conf 
+            sed -i '/SCRIPT_FILENAME/s/\/scripts/\/usr\/share\/nginx\/html\//' /etc/nginx/conf.d/default.conf
+            yum -y install mariadb mariadb-server 
+            systemctl start mariadb.service 
+            systemctl enable mariadb.service 
+            yum -y install php php-mysql php-gd libjpeg* php-ldap php-odbc php-pear php-xml php-xmlrpc php-mbstring php-bcmath php-mhash php-mcrypt 
+            MDSRING=`find / -name mbstring.so` 
+            echo extension=$MDSRING >> /etc/php.ini 
+            systemctl restart mariadb.service 
+            mysqladmin -u root password "$dbrootpassword" 
+            $(mysql $dbname -u root --password="$dbrootpassword" >/dev/null 2>&1 </dev/null); (( $? != 0 )) 
+            echo CREATE DATABASE $dbname \; > /tmp/setup.mysql 
+            echo GRANT ALL ON $dbname.* TO "$dbuser"@"localhost" IDENTIFIED BY "'$dbpassword'" \; >> /tmp/setup.mysql 
+            mysql -u root --password="$dbrootpassword" < /tmp/setup.mysql 
+            $(mysql $dbname -u root --password="$dbrootpassword" >/dev/null 2>&1 </dev/null); (( $? != 0 )) 
+            cd /root 
+            systemctl restart php-fpm.service 
+            systemctl restart nginx.service 
+            echo \<?php >  /usr/share/nginx/html/test.php 
+            echo \$conn=mysql_connect\("'127.0.0.1'", "'$dbuser'", "'$dbpassword'"\)\; >>  /usr/share/nginx/html/test.php 
+            echo if \(\$conn\){ >>  /usr/share/nginx/html/test.php 
+            echo   echo \"LNMP platform connect to mysql is successful\!\"\; >>  /usr/share/nginx/html/test.php 
+            echo   }else{  >>  /usr/share/nginx/html/test.php 
+            echo echo \"LNMP platform connect to mysql is failed\!\"\;  >>  /usr/share/nginx/html/test.php 
+            echo }  >>  /usr/share/nginx/html/test.php 
+            echo  phpinfo\(\)\;  >>  /usr/share/nginx/html/test.php 
+            echo \?\>  >>  /usr/share/nginx/html/test.php
+            ${CurlCli} -d '{"data" : "Install nginx."}'
+          - NginxUrl:
+              Ref: NginxDownloadUrl
+            DBName:
+              Ref: DBName
+            DBUser:
+              Ref: DBUser
+            DBPassword:
+              Ref: DBPassword
+            DBRootPassword:
+              Ref: DBRootPassword
+            CurlCli:
+              Fn::GetAtt:
+              - WebServerConditionHandle
+              - CurlCli
       Type: RunShellScript
       Name:
         Ref: ALIYUN::StackId
     DependsOn:
-      - WebServerConditionHandle
+    - WebServerConditionHandle
   Invocation:
     Type: ALIYUN::ECS::Invocation
     Properties:
       InstanceIds:
-        - Fn::If:
-            - IsSelectExistECS
-            - Fn::GetAtt:
-                - WebServer
-                - InstanceId
-            - Ref: ECSInstanceId
+      - Fn::If:
+        - IsSelectExistECS
+        - Fn::GetAtt:
+          - WebServer
+          - InstanceId
+        - Ref: ECSInstanceId
       CommandId:
         Ref: Command
-  WebServerConditionHandle:
-    Type: ALIYUN::ROS::WaitConditionHandle
-    Properties: {}
-    Metadata:
-      ALIYUN::ROS::Designer:
-        id: ec1625d7-b79b-496d-ba3a-5c46be0c1181
   WebServerWaitCondition:
     Type: ALIYUN::ROS::WaitCondition
     Properties:
@@ -387,21 +380,21 @@ Outputs:
     Description: URL for newly created Nginx home page.
     Value:
       Fn::Sub:
-        - 'http://${IP}:80/test.php'
-        - IP:
-            'Fn::If':
-              - IsSelectExistECS
-              - 'Fn::GetAtt':
-                  - WebServer
-                  - PublicIp
-              - 'Fn::Jq':
-                  - First
-                  - >-
-                    if .[0].PublicIpAddress != [] then .[0].PublicIpAddress[0]
-                    else .[0].EipAddress.IpAddress end
-                  - 'Fn::GetAtt':
-                      - ExistWebServer
-                      - Instances
+      - 'http://${IP}:80/test.php'
+      - IP:
+          'Fn::If':
+          - IsSelectExistECS
+          - 'Fn::GetAtt':
+            - WebServer
+            - PublicIp
+          - 'Fn::Jq':
+            - First
+            - >-
+              if .[0].PublicIpAddress != [] then .[0].PublicIpAddress[0]
+              else .[0].EipAddress.IpAddress end
+            - 'Fn::GetAtt':
+              - ExistWebServer
+              - Instances
 Metadata:
   ALIYUN::ROS::Interface:
     ParameterGroups:
