Fix multi line text format

diff --git a/documents/solution/internet-application-development/distributed-task-scheduling.yml b/documents/solution/internet-application-development/distributed-task-scheduling.yml
--- a/documents/solution/internet-application-development/distributed-task-scheduling.yml
+++ b/documents/solution/internet-application-development/distributed-task-scheduling.yml
@@ -228,22 +228,53 @@ Resources:
       Type: RunShellScript
       Timeout: 300
       CommandContent:
-        Fn::Sub: "#!/bin/bash\n\nfunction log_info() {\n    printf \"%s [INFO] %s\\\
-          n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n}\n\nfunction log_error() {\n\
-          \    printf \"%s [ERROR] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\
-          \n}\n\nfunction debug_exec(){\n    local cmd=\"$@\"\n    log_info \"$cmd\"\
-          \n    eval \"$cmd\"\n    ret=$?\n    echo \"\"\n    log_info \"$cmd, exit\
-          \ code: $ret\"\n    return $ret\n}\n\nfunction init_work(){\n  sudo yum\
-          \ -y install java-1.8.0-openjdk-devel.x86_64\n  source ~/.bash_profile\n\
-          \  \n  wget https://help-static-aliyun-doc.aliyuncs.com/demos/schedulerx-demo-0.0.1-SNAPSHOT.jar\n\
-          }\n\ncat << EOF >> ~/.bash_profile\nexport DEMO_SCHEDULERX_ENDPOINT=\"addr-hz-internal.edas.aliyun.com\"\
-          \nexport DEMO_SCHEDULERX_NAMESPACE=\"${SchedulerXNamespace}\"\nexport DEMO_SCHEDULERX_GROUPID=\"\
-          ${SchedulerXGroupId}\"\nexport DEMO_SCHEDULERX_APPKEY=\"${SchedulerXAppKey}\"\
-          \n\nexport DEMO_MYSQL_URL=\"${RdsInstance.InnerConnectionString}:3306\"\n\
-          export DEMO_MYSQL_USERNAME=\"user_test\"\nexport DEMO_MYSQL_PASSWORD=\"\
-          ${DBPassword}\"\n\nexport DEMO_USERNAME=\"${DemoUserName}\"\nexport DEMO_PASSWORD=\"\
-          ${DemoUserPassword}\"\n\nEOF\n\n\ndebug_exec init_work\nnohup java -jar\
-          \ schedulerx-demo-0.0.1-SNAPSHOT.jar > schedulerx-demo.log 2>&1 &"
+        Fn::Sub: |-
+          #!/bin/bash
+
+          function log_info() {
+              printf "%s [INFO] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+
+          function log_error() {
+              printf "%s [ERROR] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+
+          function debug_exec(){
+              local cmd="$@"
+              log_info "$cmd"
+              eval "$cmd"
+              ret=$?
+              echo ""
+              log_info "$cmd, exit code: $ret"
+              return $ret
+          }
+
+          function init_work(){
+            sudo yum -y install java-1.8.0-openjdk-devel.x86_64
+            source ~/.bash_profile
+
+            wget https://help-static-aliyun-doc.aliyuncs.com/demos/schedulerx-demo-0.0.1-SNAPSHOT.jar
+          }
+
+          cat << EOF >> ~/.bash_profile
+          export DEMO_SCHEDULERX_ENDPOINT="addr-hz-internal.edas.aliyun.com"
+          export DEMO_SCHEDULERX_NAMESPACE="${SchedulerXNamespace}"
+          export DEMO_SCHEDULERX_GROUPID="${SchedulerXGroupId}"
+          export DEMO_SCHEDULERX_APPKEY="${SchedulerXAppKey}"
+
+          export DEMO_MYSQL_URL="${RdsInstance.InnerConnectionString}:3306"
+          export DEMO_MYSQL_USERNAME="user_test"
+          export DEMO_MYSQL_PASSWORD="${DBPassword}"
+
+          export DEMO_USERNAME="${DemoUserName}"
+          export DEMO_PASSWORD="${DemoUserPassword}"
+
+          EOF
+
+
+          debug_exec init_work
+          nohup java -jar schedulerx-demo-0.0.1-SNAPSHOT.jar > schedulerx-demo.log 2>&1 &
+
 Outputs:
   DemoUserName:
     Description:
