Optimize template description and format template

diff --git a/documents/solution/internet-application-development/distributed-task-scheduling.yml b/documents/solution/internet-application-development/distributed-task-scheduling.yml
--- a/documents/solution/internet-application-development/distributed-task-scheduling.yml
+++ b/documents/solution/internet-application-development/distributed-task-scheduling.yml
@@ -1,40 +1,41 @@
 ROSTemplateFormatVersion: '2015-09-01'
 Description:
-  en: Distributed task scheduling through SchedulerX.
-  zh-cn: 通过SchedulerX实现分布式任务调度。
+  zh-cn: 创建VPC、ECS、RDS及SchedulerX资源，配置分布式任务调度环境，含安全组与网络设置，部署Java应用自动执行。
+  en: Create VPC, ECS, RDS, and SchedulerX resources, configure a distributed task
+    scheduling environment including security groups and network configurations, and
+    deploy Java applications for automatic execution.
 Parameters:
   DemoUserName:
-    ConstraintDescription:
-      zh-cn: 3 到 63 个字母组成。
-      en: 3 to 63 letters.
-    Description:
-      zh-cn: 在浏览器中登录示例应用程序时的用户名。
-      en: Username when logging into the sample application in the browser.
+    Type: String
     Label:
       zh-cn: 登录用户名
       en: Login Username
-    AllowedPattern: '^[a-zA-Z-]{3,63}$'
-    Type: String
+    Description:
+      zh-cn: 在浏览器中登录示例应用程序时的用户名。
+      en: Username when logging into the sample application in the browser.
+    ConstraintDescription:
+      zh-cn: 3 到 63 个字母组成。
+      en: 3 to 63 letters.
     AssociationProperty: AutoCompleteInput
     AssociationPropertyMetadata:
       Length: 5
       Prefix: demo-user-
       CharacterClasses:
-        - Class: lowercase
-          min: 1
+      - Class: lowercase
+        min: 1
+    AllowedPattern: ^[a-zA-Z-]{3,63}$
   DemoUserPassword:
-    NoEcho: true
     Type: String
     Label:
       en: Login Password
       zh-cn: 登录密码
     Description:
-      en: >-
-        Must contain three or more types: uppercase letters, lowercase letters, 
-        numbers, and special symbols. The length is 8 to 32 bits. 
-        Special characters include !@%^&()_+-=
-      zh-cn: '必须包含三种及以上类型：大写字母、小写字母、数字、特殊符号。长度为8～32位。特殊字符包括!@#$%^&*()_+-='
-    AssociationProperty: 'ALIYUN::RDS::Instance::AccountPassword'
+      en: 'Must contain three or more types: uppercase letters, lowercase letters,  numbers,
+        and special symbols. The length is 8 to 32 bits.  Special characters include
+        !@%^&()_+-='
+      zh-cn: 必须包含三种及以上类型：大写字母、小写字母、数字、特殊符号。长度为8～32位。特殊字符包括!@#$%^&*()_+-=
+    AssociationProperty: ALIYUN::RDS::Instance::AccountPassword
+    NoEcho: true
   ZoneId:
     Type: String
     Label:
@@ -54,52 +55,44 @@ Parameters:
       SystemDiskCategory: cloud_essd
   InstancePassword:
     Type: String
-    NoEcho: true
-    Default: null
-    Description:
-      en: >-
-        Server login password, Length 8-30, must contain three(Capital letters,
-        lowercase letters, numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special
-        symbol in)
-      zh-cn: >-
-        服务器登录密码,长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/
-        中的特殊符号）
     Label:
       en: Instance Password
       zh-cn: 实例密码
+    Description:
+      en: Server login password, Length 8-30, must contain three(Capital letters,
+        lowercase letters, numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol
+        in)
+      zh-cn: 服务器登录密码,长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ 中的特殊符号）
     ConstraintDescription:
-      en: >-
-        Length 8-30, must contain three(Capital letters, lowercase letters,
-        numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol in)
-      zh-cn: '长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;''<>,.?/ 中的特殊符号）'
-    AssociationProperty: 'ALIYUN::ECS::Instance::Password'
+      en: Length 8-30, must contain three(Capital letters, lowercase letters, numbers,
+        ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol in)
+      zh-cn: 长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ 中的特殊符号）
+    AssociationProperty: ALIYUN::ECS::Instance::Password
+    Default: null
+    NoEcho: true
   DBUserName:
     Type: String
-    ConstraintDescription:
-      en: >-
-        Consist of 2 to 32 characters of lowercase letters, underline. 
-        Must begin with a letter and be end with an alphanumeric character
-      zh-cn: >-
-        由 2 到 32 个小写字母组成，支持小写字母、数字和下划线，以小写字母开头。
     Label:
       zh-cn: RDS数据库账号
       en: RDS DB Username
+    ConstraintDescription:
+      en: Consist of 2 to 32 characters of lowercase letters, underline.  Must begin
+        with a letter and be end with an alphanumeric character
+      zh-cn: 由 2 到 32 个小写字母组成，支持小写字母、数字和下划线，以小写字母开头。
     Default: user_test
-    AllowedPattern: '^[a-z][a-z0-9_]{0,31}$'
-    ReadOnly: true
+    AllowedPattern: ^[a-z][a-z0-9_]{0,31}$
   DBPassword:
-    NoEcho: true
     Type: String
     Label:
       en: RDS Instance Password
       zh-cn: RDS数据库密码
     Description:
-      en: >-
-        Must contain three or more types: uppercase letters, lowercase letters, 
-        numbers, and special symbols. The length is 8 to 32 bits. 
-        Special characters include !@%^&()_+-=
-      zh-cn: '必须包含三种及以上类型：大写字母、小写字母、数字、特殊符号。长度为8～32位。特殊字符包括!@#$%^&*()_+-='
-    AssociationProperty: 'ALIYUN::RDS::Instance::AccountPassword'
+      en: 'Must contain three or more types: uppercase letters, lowercase letters,  numbers,
+        and special symbols. The length is 8 to 32 bits.  Special characters include
+        !@%^&()_+-='
+      zh-cn: 必须包含三种及以上类型：大写字母、小写字母、数字、特殊符号。长度为8～32位。特殊字符包括!@#$%^&*()_+-=
+    AssociationProperty: ALIYUN::RDS::Instance::AccountPassword
+    NoEcho: true
   DBInstanceClass:
     Type: String
     Label:
@@ -120,16 +113,18 @@ Parameters:
       en: SchedulerX Namespace
       zh-cn: SchedulerX命名空间
     Description:
-      en: Please enter the namespace obtained in the access configuration of the SchedulerX console.
+      en: Please enter the namespace obtained in the access configuration of the SchedulerX
+        console.
       zh-cn: 请输入在SchedulerX控制台的接入配置中获取的命名空间。
-    AllowedPattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
+    AllowedPattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
   SchedulerXGroupId:
     Type: String
     Label:
       en: SchedulerX GroupId
       zh-cn: SchedulerX应用ID
     Description:
-      en: Please enter the namespace obtained in the access configuration of the SchedulerX console.
+      en: Please enter the namespace obtained in the access configuration of the SchedulerX
+        console.
       zh-cn: 请输入在SchedulerX控制台的接入配置中获取的应用ID。
   SchedulerXAppKey:
     Type: String
@@ -137,52 +132,53 @@ Parameters:
       en: SchedulerX AppKey
       zh-cn: SchedulerX应用密钥
     Description:
-      en: Please enter the namespace obtained in the access configuration of the SchedulerX console.
+      en: Please enter the namespace obtained in the access configuration of the SchedulerX
+        console.
       zh-cn: 请输入在SchedulerX控制台的接入配置中获取的应用密钥。
   CommonName:
     Type: String
     Default: scheduler-demo
 Resources:
   Vpc:
-    Type: 'ALIYUN::ECS::VPC'
+    Type: ALIYUN::ECS::VPC
     Properties:
       CidrBlock: 192.168.0.0/16
       VpcName:
         Fn::Sub: ${CommonName}-vpc
   VSwitch:
-    Type: 'ALIYUN::ECS::VSwitch'
+    Type: ALIYUN::ECS::VSwitch
     Properties:
+      ZoneId:
+        Ref: ZoneId
       VpcId:
         Ref: Vpc
       CidrBlock: 192.168.0.0/24
-      ZoneId:
-        Ref: ZoneId
       VSwitchName:
         Fn::Sub: ${CommonName}-vsw
   SecurityGroup:
-    Type: 'ALIYUN::ECS::SecurityGroup'
+    Type: ALIYUN::ECS::SecurityGroup
     Properties:
       VpcId:
         Ref: Vpc
       SecurityGroupName:
         Fn::Sub: ${CommonName}-sg
       SecurityGroupIngress:
-        - PortRange: 22/22
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: tcp
-        - PortRange: 80/80
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: tcp
-        - PortRange: '-1/-1'
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: icmp
+      - PortRange: 22/22
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: tcp
+      - PortRange: 80/80
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: tcp
+      - PortRange: -1/-1
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: icmp
   EcsInstance:
-    Type: 'ALIYUN::ECS::InstanceGroup'
+    Type: ALIYUN::ECS::InstanceGroup
     Properties:
-      VpcId:
-        Ref: Vpc
       ZoneId:
         Ref: ZoneId
+      VpcId:
+        Ref: Vpc
       VSwitchId:
         Ref: VSwitch
       SecurityGroupId:
@@ -198,24 +194,24 @@ Resources:
       Password:
         Ref: InstancePassword
   RdsInstance:
-    Type: 'ALIYUN::RDS::DBInstance'
+    Type: ALIYUN::RDS::DBInstance
     Properties:
-      DBInstanceClass:
-        Ref: DBInstanceClass
       ZoneId:
         Ref: ZoneId
+      SlaveZoneIds:
+      - Auto
+      VpcId:
+        Ref: Vpc
+      VSwitchId:
+        Ref: VSwitch
+      DBInstanceClass:
+        Ref: DBInstanceClass
       DBInstanceStorage: 40
       Category: Basic
       DBInstanceStorageType: cloud_essd
-      VSwitchId:
-        Ref: VSwitch
       Engine: MySQL
-      VpcId:
-        Ref: Vpc
-      SlaveZoneIds:
-        - Auto
       EngineVersion: '8.0'
-      SecurityIPList: '192.168.0.0/24'
+      SecurityIPList: 192.168.0.0/24
       MasterUsername:
         Ref: DBUserName
       MasterUserPassword:
@@ -226,108 +222,78 @@ Resources:
     Properties:
       InstanceIds:
         Fn::GetAtt:
-          - EcsInstance
-          - InstanceIds
+        - EcsInstance
+        - InstanceIds
       Sync: true
       Type: RunShellScript
       Timeout: 300
       CommandContent:
-        Fn::Sub: |-
-          #!/bin/bash
-
-          function log_info() {
-              printf "%s [INFO] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
-          }
-          
-          function log_error() {
-              printf "%s [ERROR] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
-          }
-          
-          function debug_exec(){
-              local cmd="$@"
-              log_info "$cmd"
-              eval "$cmd"
-              ret=$?
-              echo ""
-              log_info "$cmd, exit code: $ret"
-              return $ret
-          }
-          
-          function init_work(){
-            sudo yum -y install java-1.8.0-openjdk-devel.x86_64
-            source ~/.bash_profile
-            
-            wget https://help-static-aliyun-doc.aliyuncs.com/demos/schedulerx-demo-0.0.1-SNAPSHOT.jar
-          }
-          
-          cat << EOF >> ~/.bash_profile
-          export DEMO_SCHEDULERX_ENDPOINT="addr-hz-internal.edas.aliyun.com"
-          export DEMO_SCHEDULERX_NAMESPACE="${SchedulerXNamespace}"
-          export DEMO_SCHEDULERX_GROUPID="${SchedulerXGroupId}"
-          export DEMO_SCHEDULERX_APPKEY="${SchedulerXAppKey}"
-          
-          export DEMO_MYSQL_URL="${RdsInstance.InnerConnectionString}:3306"
-          export DEMO_MYSQL_USERNAME="user_test"
-          export DEMO_MYSQL_PASSWORD="${DBPassword}"
-          
-          export DEMO_USERNAME="${DemoUserName}"
-          export DEMO_PASSWORD="${DemoUserPassword}"
-        
-          EOF
-          
-          
-          debug_exec init_work
-          nohup java -jar schedulerx-demo-0.0.1-SNAPSHOT.jar > schedulerx-demo.log 2>&1 &
+        Fn::Sub: "#!/bin/bash\n\nfunction log_info() {\n    printf \"%s [INFO] %s\\\
+          n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n}\n\nfunction log_error() {\n\
+          \    printf \"%s [ERROR] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\
+          \n}\n\nfunction debug_exec(){\n    local cmd=\"$@\"\n    log_info \"$cmd\"\
+          \n    eval \"$cmd\"\n    ret=$?\n    echo \"\"\n    log_info \"$cmd, exit\
+          \ code: $ret\"\n    return $ret\n}\n\nfunction init_work(){\n  sudo yum\
+          \ -y install java-1.8.0-openjdk-devel.x86_64\n  source ~/.bash_profile\n\
+          \  \n  wget https://help-static-aliyun-doc.aliyuncs.com/demos/schedulerx-demo-0.0.1-SNAPSHOT.jar\n\
+          }\n\ncat << EOF >> ~/.bash_profile\nexport DEMO_SCHEDULERX_ENDPOINT=\"addr-hz-internal.edas.aliyun.com\"\
+          \nexport DEMO_SCHEDULERX_NAMESPACE=\"${SchedulerXNamespace}\"\nexport DEMO_SCHEDULERX_GROUPID=\"\
+          ${SchedulerXGroupId}\"\nexport DEMO_SCHEDULERX_APPKEY=\"${SchedulerXAppKey}\"\
+          \n\nexport DEMO_MYSQL_URL=\"${RdsInstance.InnerConnectionString}:3306\"\n\
+          export DEMO_MYSQL_USERNAME=\"user_test\"\nexport DEMO_MYSQL_PASSWORD=\"\
+          ${DBPassword}\"\n\nexport DEMO_USERNAME=\"${DemoUserName}\"\nexport DEMO_PASSWORD=\"\
+          ${DemoUserPassword}\"\n\nEOF\n\n\ndebug_exec init_work\nnohup java -jar\
+          \ schedulerx-demo-0.0.1-SNAPSHOT.jar > schedulerx-demo.log 2>&1 &"
 Outputs:
-    DemoUserName:
-      Description:
-        en: Login Username.
-        zh-cn: 登录用户名。
-      Value:
-        Ref: DemoUserName
-    DemoUrl:
-      Description:
-        zh-cn: 体验地址。
-        en: Demo URL.
-      Value:
-        'Fn::Sub':
-          - 'http://${PublicIp}/schedulerx-demo'
-          - PublicIp:
-              'Fn::Select':
-                - 0
-                - 'Fn::GetAtt':
-                    - EcsInstance
-                    - PublicIps
+  DemoUserName:
+    Description:
+      en: Login Username.
+      zh-cn: 登录用户名。
+    Value:
+      Ref: DemoUserName
+  DemoUrl:
+    Description:
+      zh-cn: 体验地址。
+      en: Demo URL.
+    Value:
+      Fn::Sub:
+      - http://${PublicIp}/schedulerx-demo
+      - PublicIp:
+          Fn::Select:
+          - 0
+          - Fn::GetAtt:
+            - EcsInstance
+            - PublicIps
 Metadata:
   ALIYUN::ROS::Interface:
     ParameterGroups:
-      - Parameters:
-          - DemoUserName
-          - DemoUserPassword
-        Label:
-          en: Application login information configuration
-          zh-cn: 应用登录信息配置
-      - Parameters:
-          - ZoneId
-          - InstanceType
-          - InstancePassword
-        Label:
-          en: ECS configuration
-          zh-cn: ECS 参数配置
-      - Parameters:
-          - DBUserName
-          - DBPassword
-          - DBInstanceClass
-        Label:
-          en: Database configuration
-          zh-cn: 数据库配置
-      - Parameters:
-        - SchedulerXNamespace
-        - SchedulerXGroupId
-        - SchedulerXAppKey
-        Label:
-          en: SchedulerX configuration
-          zh-cn: SchedulerX配置
+    - Parameters:
+      - DemoUserName
+      - DemoUserPassword
+      Label:
+        en: Application login information configuration
+        zh-cn: 应用登录信息配置
+    - Parameters:
+      - ZoneId
+      - InstanceType
+      - InstancePassword
+      Label:
+        en: ECS configuration
+        zh-cn: ECS 参数配置
+    - Parameters:
+      - DBUserName
+      - DBPassword
+      - DBInstanceClass
+      Label:
+        en: Database configuration
+        zh-cn: 数据库配置
+    - Parameters:
+      - SchedulerXNamespace
+      - SchedulerXGroupId
+      - SchedulerXAppKey
+      Label:
+        en: SchedulerX configuration
+        zh-cn: SchedulerX配置
     TemplateTags:
     - acs:technical-solution:internet-application-development:通过SchedulerX实现分布式任务调度-tech_solu_143
     Hidden:
diff --git a/documents/solution/internet-application-development/process-data-with-lindorm.yml b/documents/solution/internet-application-development/process-data-with-lindorm.yml
--- a/documents/solution/internet-application-development/process-data-with-lindorm.yml
+++ b/documents/solution/internet-application-development/process-data-with-lindorm.yml
@@ -1,7 +1,10 @@
 ROSTemplateFormatVersion: '2015-09-01'
 Description:
-  en: Lindorm one-stop processing of pan-time series data.
-  zh-cn: Lindorm泛时序数据一站式处理。
+  zh-cn: 创建VPC、交换机、安全组，部署Lindorm数据库(2节点)、ECS实例(1台)及应用，支持泛时序数据一站式处理。
+  en: Create a Virtual Private Cloud (VPC), switches, security groups, deploy a Lindorm
+    database cluster (with 2 nodes), provision an Elastic Compute Service (ECS) instance
+    (1 unit), and set up the application to facilitate end-to-end processing of pan-temporal
+    data.
 Parameters:
   ZoneId:
     Type: String
@@ -22,73 +25,69 @@ Parameters:
       SystemDiskCategory: cloud_essd
   InstancePassword:
     Type: String
-    NoEcho: true
-    Default: null
-    Description:
-      en: >-
-        Server login password, Length 8-30, must contain three(Capital letters,
-        lowercase letters, numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special
-        symbol in)
-      zh-cn: >-
-        服务器登录密码,长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/
-        中的特殊符号）
     Label:
       en: Instance Password
       zh-cn: 实例密码
+    Description:
+      en: Server login password, Length 8-30, must contain three(Capital letters,
+        lowercase letters, numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol
+        in)
+      zh-cn: 服务器登录密码,长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ 中的特殊符号）
     ConstraintDescription:
-      en: >-
-        Length 8-30, must contain three(Capital letters, lowercase letters,
-        numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol in)
-      zh-cn: '长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;''<>,.?/ 中的特殊符号）'
-    AssociationProperty: 'ALIYUN::ECS::Instance::Password'
+      en: Length 8-30, must contain three(Capital letters, lowercase letters, numbers,
+        ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol in)
+      zh-cn: 长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ 中的特殊符号）
+    AssociationProperty: ALIYUN::ECS::Instance::Password
+    Default: null
+    NoEcho: true
   CommonName:
     Type: String
     Default: lindorm-demo
 Resources:
   Vpc:
-    Type: 'ALIYUN::ECS::VPC'
+    Type: ALIYUN::ECS::VPC
     Properties:
       CidrBlock: 192.168.0.0/16
       VpcName:
         Fn::Sub: ${CommonName}-vpc
   VSwitch:
-    Type: 'ALIYUN::ECS::VSwitch'
+    Type: ALIYUN::ECS::VSwitch
     Properties:
+      ZoneId:
+        Ref: ZoneId
       VpcId:
         Ref: Vpc
       CidrBlock: 192.168.0.0/24
-      ZoneId:
-        Ref: ZoneId
       VSwitchName:
         Fn::Sub: ${CommonName}-vsw
   SecurityGroup:
-    Type: 'ALIYUN::ECS::SecurityGroup'
+    Type: ALIYUN::ECS::SecurityGroup
     Properties:
       VpcId:
         Ref: Vpc
       SecurityGroupName:
         Fn::Sub: ${CommonName}-sg
       SecurityGroupIngress:
-        - PortRange: 22/22
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: tcp
-        - PortRange: 80/80
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: tcp
-        - PortRange: '-1/-1'
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: icmp
+      - PortRange: 22/22
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: tcp
+      - PortRange: 80/80
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: tcp
+      - PortRange: -1/-1
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: icmp
   LindormInstance:
-    Type: 'ALIYUN::Lindorm::Instance'
+    Type: ALIYUN::Lindorm::Instance
     Properties:
-      InstanceStorage: 160
       ZoneId:
         Ref: ZoneId
-      InstanceChargeType: POSTPAY
-      VSwitchId:
-        Ref: VSwitch
       VpcId:
         Ref: Vpc
+      VSwitchId:
+        Ref: VSwitch
+      InstanceStorage: 160
+      InstanceChargeType: POSTPAY
       LindormSpec: lindorm.g.xlarge
       LindormNum: 2
       SolrSpec: lindorm.g.xlarge
@@ -97,12 +96,12 @@ Resources:
       InstanceName:
         Fn::Sub: ${CommonName}-lindorm
   EcsInstance:
-    Type: 'ALIYUN::ECS::InstanceGroup'
+    Type: ALIYUN::ECS::InstanceGroup
     Properties:
-      VpcId:
-        Ref: Vpc
       ZoneId:
         Ref: ZoneId
+      VpcId:
+        Ref: Vpc
       VSwitchId:
         Ref: VSwitch
       SecurityGroupId:
@@ -121,40 +120,20 @@ Resources:
     Type: ALIYUN::ECS::RunCommand
     Properties:
       InstanceIds:
-        - Ref: EcsInstance
+      - Ref: EcsInstance
       Sync: true
       Type: RunShellScript
       Timeout: 300
       CommandContent:
-        Fn::Sub: |-
-          #!/bin/bash
-
-          function log_info() {
-              printf "%s [INFO] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
-          }
-          
-          function log_error() {
-              printf "%s [ERROR] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
-          }
-          
-          function debug_exec(){
-              local cmd="$@"
-              log_info "$cmd"
-              eval "$cmd"
-              ret=$?
-              echo ""
-              log_info "$cmd, exit code: $ret"
-              return $ret
-          }
-          
-          function init_work(){
-            yum upgrade & yum install -y python3 cryptography==3.4.8
-            
-            wget -O lindorm-cli-linux-latest.tar.gz https://tsdbtools.oss-cn-hangzhou.aliyuncs.com/lindorm-cli-linux-latest.tar.gz
-            tar zxvf lindorm-cli-linux-latest.tar.gz
-          }
-          
-          debug_exec init_work
+        Fn::Sub: "#!/bin/bash\n\nfunction log_info() {\n    printf \"%s [INFO] %s\\\
+          n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n}\n\nfunction log_error() {\n\
+          \    printf \"%s [ERROR] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\
+          \n}\n\nfunction debug_exec(){\n    local cmd=\"$@\"\n    log_info \"$cmd\"\
+          \n    eval \"$cmd\"\n    ret=$?\n    echo \"\"\n    log_info \"$cmd, exit\
+          \ code: $ret\"\n    return $ret\n}\n\nfunction init_work(){\n  yum upgrade\
+          \ & yum install -y python3 cryptography==3.4.8\n  \n  wget -O lindorm-cli-linux-latest.tar.gz\
+          \ https://tsdbtools.oss-cn-hangzhou.aliyuncs.com/lindorm-cli-linux-latest.tar.gz\n\
+          \  tar zxvf lindorm-cli-linux-latest.tar.gz\n}\n\ndebug_exec init_work"
 Outputs:
   EcsLoginAddress:
     Description:
@@ -165,10 +144,10 @@ Outputs:
 Metadata:
   ALIYUN::ROS::Interface:
     ParameterGroups:
-      - Parameters:
-        - ZoneId
-        - InstanceType
-        - InstancePassword
+    - Parameters:
+      - ZoneId
+      - InstanceType
+      - InstancePassword
     TemplateTags:
     - acs:technical-solution:internet-application-development:Lindorm泛时序数据一站式处理-tech_solu_141
     Hidden:
diff --git a/documents/solution/internet-application-development/rapidly-enterprise-portal.yml b/documents/solution/internet-application-development/rapidly-enterprise-portal.yml
--- a/documents/solution/internet-application-development/rapidly-enterprise-portal.yml
+++ b/documents/solution/internet-application-development/rapidly-enterprise-portal.yml
@@ -1,129 +1,125 @@
 ROSTemplateFormatVersion: '2015-09-01'
 Description:
-  en: Rapidly set up a enterprise portal.
-  zh-cn: 快速搭建企业门户网站。
+  zh-cn: 创建VPC、ECS实例、安全组，配置域名解析，自动部署Java应用，实现快速搭建企业门户网站。
+  en: Create a Virtual Private Cloud (VPC), Elastic Compute Service (ECS) instances,
+    Security Groups, configure Domain Name System (DNS) resolution, and automatically
+    deploy Java applications to facilitate the rapid setup of an enterprise portal
+    website.
+Conditions:
+  DnsRecord:
+    Fn::Not:
+      Fn::Equals:
+      - Ref: DomainName
+      - null
+  DomainPrefixIsNull:
+    Fn::And:
+    - DnsRecord
+    - Fn::Equals:
+      - null
+      - Fn::GetJsonValue:
+        - DomainPrefix
+        - Ref: DomainName
 Parameters:
-  CommonName:
-    Type: String
-    Default: portal
-  ZoneId:
-    Type: String
-    AssociationProperty: 'ALIYUN::ECS::Instance::ZoneId'
-    AssociationPropertyMetadata:
-      AutoSelectFirst: true
-    Label:
-      en: Availability Zone
-      zh-cn: 可用区
   InstanceType:
     Type: String
-    AssociationProperty: 'ALIYUN::ECS::Instance::InstanceType'
-    AssociationPropertyMetadata:
-      SpotStrategy: SpotAsPriceGo
-      InstanceChargeType: PostPaid
-      SystemDiskCategory: cloud_essd
-      ZoneId: ${ZoneId}
     Label:
       en: Instance Type
       zh-cn: 实例规格
     Description:
       zh-cn: 本方案会创建一个抢占式实例，并且自动部署java服务。
-      en: >-
-        This solution will create a spot instance and automatically deploy a
-        java service.
+      en: This solution will create a spot instance and automatically deploy a java
+        service.
+    AssociationProperty: ALIYUN::ECS::Instance::InstanceType
+    AssociationPropertyMetadata:
+      SpotStrategy: SpotAsPriceGo
+      InstanceChargeType: PostPaid
+      SystemDiskCategory: cloud_essd
+      ZoneId: ${ZoneId}
     Default: ecs.c7.large
   InstancePassword:
-    NoEcho: true
     Type: String
-    Description:
-      en: >-
-        Server login password, Length 8-30, must contain three(Capital letters,
-        lowercase letters, numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special
-        symbol in)
-      zh-cn: >-
-        服务器登录密码，长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/
-        中的特殊符号）
     Label:
       en: Instance Password
       zh-cn: 实例密码
+    Description:
+      en: Server login password, Length 8-30, must contain three(Capital letters,
+        lowercase letters, numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol
+        in)
+      zh-cn: 服务器登录密码，长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ 中的特殊符号）
     ConstraintDescription:
-      en: >-
-        Length 8-30, must contain three(Capital letters, lowercase letters,
-        numbers, ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol in)
-      zh-cn: '长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;''<>,.?/ 中的特殊符号）'
-    AssociationProperty: 'ALIYUN::ECS::Instance::Password'
+      en: Length 8-30, must contain three(Capital letters, lowercase letters, numbers,
+        ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ Special symbol in)
+      zh-cn: 长度8-30，必须包含三项（大写字母、小写字母、数字、 ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/ 中的特殊符号）
+    AssociationProperty: ALIYUN::ECS::Instance::Password
     Default: null
+    NoEcho: true
   DomainName:
     Type: String
     Label:
       en: Website domain name
       zh-cn: 网站域名
-    AssociationProperty: 'ALIYUN::DomainName'
     Description:
-      en: >-
-        Please enter the subdomain name under the current account, such as example.aliyun.com.
-        If it is a domestic region, you need to fill in the registered
-        domain name, otherwise the website will not be able to plan.
-      zh-cn: >-
-        请输入当前账号下的域名，例如example.aliyun.com。如果是境内地域则需要填写已完成备案的域名，否则会导致网站无法访问。
+      en: Please enter the subdomain name under the current account, such as example.aliyun.com.
+        If it is a domestic region, you need to fill in the registered domain name,
+        otherwise the website will not be able to plan.
+      zh-cn: 请输入当前账号下的域名，例如example.aliyun.com。如果是境内地域则需要填写已完成备案的域名，否则会导致网站无法访问。
+    AssociationProperty: ALIYUN::DomainName
     Default: null
-Conditions:
-  DnsRecord:
-    Fn::Not:
-      Fn::Equals:
-        - Ref: DomainName
-        - null
-  DomainPrefixIsNull:
-    Fn::And:
-      - DnsRecord
-      - Fn::Equals:
-          - null
-          - Fn::GetJsonValue:
-              - DomainPrefix
-              - Ref: DomainName
+  CommonName:
+    Type: String
+    Default: portal
+  ZoneId:
+    Type: String
+    Label:
+      en: Availability Zone
+      zh-cn: 可用区
+    AssociationProperty: ALIYUN::ECS::Instance::ZoneId
+    AssociationPropertyMetadata:
+      AutoSelectFirst: true
 Resources:
   Vpc:
-    Type: 'ALIYUN::ECS::VPC'
+    Type: ALIYUN::ECS::VPC
     Properties:
       CidrBlock: 192.168.0.0/16
       VpcName:
         Fn::Sub: ${CommonName}-vpc
   VSwitch:
-    Type: 'ALIYUN::ECS::VSwitch'
+    Type: ALIYUN::ECS::VSwitch
     Properties:
+      ZoneId:
+        Ref: ZoneId
       VpcId:
         Ref: Vpc
       CidrBlock: 192.168.0.0/24
-      ZoneId:
-        Ref: ZoneId
       VSwitchName:
         Fn::Sub: ${CommonName}-vsw
   SecurityGroup:
-    Type: 'ALIYUN::ECS::SecurityGroup'
+    Type: ALIYUN::ECS::SecurityGroup
     Properties:
       VpcId:
         Ref: Vpc
       SecurityGroupName:
         Fn::Sub: ${CommonName}-sg
       SecurityGroupIngress:
-        - PortRange: 22/22
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: tcp
-        - PortRange: 443/443
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: tcp
-        - PortRange: 80/80
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: tcp
-        - PortRange: 3306/3306
-          SourceCidrIp: 0.0.0.0/0
-          IpProtocol: tcp
+      - PortRange: 22/22
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: tcp
+      - PortRange: 443/443
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: tcp
+      - PortRange: 80/80
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: tcp
+      - PortRange: 3306/3306
+        SourceCidrIp: 0.0.0.0/0
+        IpProtocol: tcp
   EcsInstance:
-    Type: 'ALIYUN::ECS::InstanceGroup'
+    Type: ALIYUN::ECS::InstanceGroup
     Properties:
-      VpcId:
-        Ref: Vpc
       ZoneId:
         Ref: ZoneId
+      VpcId:
+        Ref: Vpc
       VSwitchId:
         Ref: VSwitch
       SecurityGroupId:
@@ -140,153 +136,113 @@ Resources:
       Password:
         Ref: InstancePassword
   InstallJava:
-    Type: 'ALIYUN::ECS::RunCommand'
+    Type: ALIYUN::ECS::RunCommand
     Properties:
       InstanceIds:
         Fn::GetAtt:
-          - EcsInstance
-          - InstanceIds
+        - EcsInstance
+        - InstanceIds
       Type: RunShellScript
       Sync: true
       Timeout: 3600
       CommandContent:
-        Fn::Sub: |-
-          #!/bin/bash
-
-          # script exit code:
-          # 0 - success
-          # 1 - unsupported system
-          # 2 - network not available
-          # 3 - failed install java 
-
-          # 环境变量配置
-          export PATH=/usr/local/bin:$PATH
-
-          function unsupported_system() {
-              log_fatal 1 "Unsupported System: $1"
-          }
-
-          function log_info() {
-              printf "%s [INFO] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
-          }
-
-          function log_error() {
-              printf "%s [ERROR] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
-          }
-
-          function log_fatal() {
-              printf "\n========================================================================\n"
-              printf "%s [FATAL] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$2"
-              printf "\n========================================================================\n"
-              exit $1
-          }
-
-          function debug_exec(){
-              local cmd="$@"
-              log_info "$cmd"
-              eval "$cmd"
-              ret=$?
-              echo ""
-              log_info "$cmd, exit code: $ret"
-              return $ret
-          }
-
-          function install_java() {
-              log_info "install java"
-              yum upgrade & yum install java-1.8.0-openjdk-devel -y
-          }
-
-          log_info "System Information:"
-          if ! lsb_release -a; then
-              unsupported_system
-          fi;
-          echo ""
-
-          if ! debug_exec install_java; then
-              log_fatal 3 "install java failed"
-          fi
+        Fn::Sub: "#!/bin/bash\n\n# script exit code:\n# 0 - success\n# 1 - unsupported\
+          \ system\n# 2 - network not available\n# 3 - failed install java \n\n# 环境变量配置\n\
+          export PATH=/usr/local/bin:$PATH\n\nfunction unsupported_system() {\n  \
+          \  log_fatal 1 \"Unsupported System: $1\"\n}\n\nfunction log_info() {\n\
+          \    printf \"%s [INFO] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n\
+          }\n\nfunction log_error() {\n    printf \"%s [ERROR] %s\\n\" \"$(date '+%Y-%m-%d\
+          \ %H:%M:%S')\" \"$1\"\n}\n\nfunction log_fatal() {\n    printf \"\\n========================================================================\\\
+          n\"\n    printf \"%s [FATAL] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"\
+          $2\"\n    printf \"\\n========================================================================\\\
+          n\"\n    exit $1\n}\n\nfunction debug_exec(){\n    local cmd=\"$@\"\n  \
+          \  log_info \"$cmd\"\n    eval \"$cmd\"\n    ret=$?\n    echo \"\"\n   \
+          \ log_info \"$cmd, exit code: $ret\"\n    return $ret\n}\n\nfunction install_java()\
+          \ {\n    log_info \"install java\"\n    yum upgrade & yum install java-1.8.0-openjdk-devel\
+          \ -y\n}\n\nlog_info \"System Information:\"\nif ! lsb_release -a; then\n\
+          \    unsupported_system\nfi;\necho \"\"\n\nif ! debug_exec install_java;\
+          \ then\n    log_fatal 3 \"install java failed\"\nfi"
   DomainRecord:
-    Type: 'ALIYUN::DNS::DomainRecord'
+    Type: ALIYUN::DNS::DomainRecord
     Condition: DnsRecord
     Properties:
       Type: A
       RR:
         Fn::If:
-          - DomainPrefixIsNull
-          - '@'
-          - Fn::GetJsonValue:
-              - DomainPrefix
-              - Ref: DomainName
+        - DomainPrefixIsNull
+        - '@'
+        - Fn::GetJsonValue:
+          - DomainPrefix
+          - Ref: DomainName
       DomainName:
         Fn::GetJsonValue:
-          - DomainName
-          - Ref: DomainName
+        - DomainName
+        - Ref: DomainName
       Value:
         Fn::Select:
-          - 0
-          - Fn::GetAtt:
-              - EcsInstance
-              - PublicIps
+        - 0
+        - Fn::GetAtt:
+          - EcsInstance
+          - PublicIps
 Outputs:
   WebUrl:
     Description:
       zh-cn: Web 访问地址(Ip)。
       en: The Addresses of Web(Ip).
     Value:
-      'Fn::Sub':
-        - 'http://${ServerAddress}'
-        - ServerAddress:
-            'Fn::Select':
-              - 0
-              - 'Fn::GetAtt':
-                  - EcsInstance
-                  - PublicIps
+      Fn::Sub:
+      - http://${ServerAddress}
+      - ServerAddress:
+          Fn::Select:
+          - 0
+          - Fn::GetAtt:
+            - EcsInstance
+            - PublicIps
   WebDomain:
-    Condition: DnsRecord
     Description:
       zh-cn: Web 访问地址(域名)。
       en: The Addresses of Web(Domain).
+    Condition: DnsRecord
     Value:
       Fn::Sub:
-        - 'http://${DomainName}'
-        - DomainName:
-            Fn::If:
-              - DomainPrefixIsNull
+      - http://${DomainName}
+      - DomainName:
+          Fn::If:
+          - DomainPrefixIsNull
+          - Fn::GetJsonValue:
+            - DomainName
+            - Ref: DomainName
+          - Fn::Join:
+            - .
+            - - Fn::GetJsonValue:
+                - DomainPrefix
+                - Ref: DomainName
               - Fn::GetJsonValue:
-                  - DomainName
-                  - Ref: DomainName
-              - Fn::Join:
-                  - '.'
-                  - - Fn::GetJsonValue:
-                        - DomainPrefix
-                        - Ref: DomainName
-                    - Fn::GetJsonValue:
-                        - DomainName
-                        - Ref: DomainName
+                - DomainName
+                - Ref: DomainName
   EcsLoginAddress:
     Description:
       zh-cn: ECS登录地址。
       en: Ecs login address.
     Value:
-      'Fn::Sub':
-        - >-
-          https://ecs-workbench.aliyun.com/?from=EcsConsole&instanceType=ecs&regionId=${Region}&instanceId=${InstanceId}
-        - InstanceId:
-            'Fn::Select':
-              - 0
-              - 'Fn::GetAtt':
-                  - EcsInstance
-                  - InstanceIds
-          Region:
-            Ref: 'ALIYUN::Region'
+      Fn::Sub:
+      - https://ecs-workbench.aliyun.com/?from=EcsConsole&instanceType=ecs&regionId=${Region}&instanceId=${InstanceId}
+      - InstanceId:
+          Fn::Select:
+          - 0
+          - Fn::GetAtt:
+            - EcsInstance
+            - InstanceIds
+        Region:
+          Ref: ALIYUN::Region
 Metadata:
-  'ALIYUN::ROS::Interface':
+  ALIYUN::ROS::Interface:
     ParameterGroups:
-      - Parameters:
-          - InstanceType
-          - InstancePassword
-          - DomainName
+    - Parameters:
+      - InstanceType
+      - InstancePassword
+      - DomainName
     TemplateTags:
-      - acs:technical-solution:internet-application-development:快速搭建企业门户网站-tech_solu_102
+    - acs:technical-solution:internet-application-development:快速搭建企业门户网站-tech_solu_102
     Hidden:
-      - CommonName
+    - CommonName
diff --git a/examples/ai/ecs-instance-flowise.yml b/examples/ai/ecs-instance-flowise.yml
--- a/examples/ai/ecs-instance-flowise.yml
+++ b/examples/ai/ecs-instance-flowise.yml
@@ -1,17 +1,21 @@
 ROSTemplateFormatVersion: '2015-09-01'
 Description:
-  en: Build the LLM orchestration flow & AI agents service Flowise on the ECS instance (Ubuntu 22.04).
-  zh-cn: 在ECS实例（Ubuntu 22.04）上搭建LLM流程编排和AI代理服务Flowise。
+  zh-cn: 创建Ubuntu 22.04 ECS实例，配置安全组与网络，自动安装Node.js与Flowise AI代理服务，提供外部访问URL。
+  en: Create an Ubuntu 22.04 ECS instance, configure security groups and networking,
+    automate the installation of Node.js alongside the Flowise AI agent service, and
+    provision an external access URL.
 Parameters:
   ZoneId:
     Type: String
     Label:
       en: Availability Zone
       zh-cn: 可用区ID
-    AssociationProperty: ALIYUN::ECS::Instance:ZoneId
     Description:
-      en: <b><font color='blue'>This template will clone the FlowiseAI/Flowise repository from GitHub using the Git tool. There may be network problems when using it in domestic regions. You can switch to overseas regions.</font></b>
+      en: <b><font color='blue'>This template will clone the FlowiseAI/Flowise repository
+        from GitHub using the Git tool. There may be network problems when using it
+        in domestic regions. You can switch to overseas regions.</font></b>
       zh-cn: <b><font color='blue'>本模板会使用Git工具从GitHub上克隆（clone）FlowiseAI/Flowise仓库，在国内地域使用可能会有网络问题，可切换至海外地域。</font></b>
+    AssociationProperty: ALIYUN::ECS::Instance:ZoneId
   InstanceType:
     Type: String
     Label:
@@ -54,7 +58,7 @@ Parameters:
           Fn::Equals:
           - ${SelectInstance}
           - false
-    Default:
+    Default: null
     AllowedPattern: '[0-9A-Za-z\_\-\&:;''<>,=%`~!@#\(\)\$\^\*\+\|\{\}\[\]\.\?\/]+$'
     MinLength: 8
     MaxLength: 30
@@ -122,37 +126,19 @@ Resources:
       Type: RunShellScript
       Sync: true
       Timeout: 1800
-      CommandContent: |
-        #!/bin/bash
-        echo "#########################"
-        echo "# Install NodeJS"
-        echo "#########################"
-        git clone https://github.com/nvm-sh/nvm.git /opt/nvm && cd /opt/nvm
-        ret_code=$?
-        if [ $ret_code -ne 0 ]; then
-          echo "Git clone https://github.com/nvm-sh/nvm.git failed. Exiting."
-          exit $ret_code
-        fi
-        ./install.sh
-        export NVM_DIR="$HOME/.nvm"
-        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
-        nvm install 22
-        npm config set registry https://registry.npmmirror.com
-        npm i -g pnpm
-        
-        echo "#########################"
-        echo "# Install Flowise"
-        echo "#########################"
-        git clone --depth 1 https://github.com/FlowiseAI/Flowise.git /opt/Flowise && cd /opt/Flowise
-        ret_code=$?
-        if [ $ret_code -ne 0 ]; then
-          echo "Git clone https://github.com/FlowiseAI/Flowise.git failed. Exiting."
-          exit $ret_code
-        fi
-        pnpm install
-        pnpm build
-        nohup pnpm start > flowise.log 2>&1 &
+      CommandContent: "#!/bin/bash\necho \"#########################\"\necho \"# Install\
+        \ NodeJS\"\necho \"#########################\"\ngit clone https://github.com/nvm-sh/nvm.git\
+        \ /opt/nvm && cd /opt/nvm\nret_code=$?\nif [ $ret_code -ne 0 ]; then\n  echo\
+        \ \"Git clone https://github.com/nvm-sh/nvm.git failed. Exiting.\"\n  exit\
+        \ $ret_code\nfi\n./install.sh\nexport NVM_DIR=\"$HOME/.nvm\"\n[ -s \"$NVM_DIR/nvm.sh\"\
+        \ ] && \\. \"$NVM_DIR/nvm.sh\"\n[ -s \"$NVM_DIR/bash_completion\" ] && \\\
+        . \"$NVM_DIR/bash_completion\"\nnvm install 22\nnpm config set registry https://registry.npmmirror.com\n\
+        npm i -g pnpm\n\necho \"#########################\"\necho \"# Install Flowise\"\
+        \necho \"#########################\"\ngit clone --depth 1 https://github.com/FlowiseAI/Flowise.git\
+        \ /opt/Flowise && cd /opt/Flowise\nret_code=$?\nif [ $ret_code -ne 0 ]; then\n\
+        \  echo \"Git clone https://github.com/FlowiseAI/Flowise.git failed. Exiting.\"\
+        \n  exit $ret_code\nfi\npnpm install\npnpm build\nnohup pnpm start > flowise.log\
+        \ 2>&1 &\n"
 Outputs:
   FlowiseUrl:
     Description: Flowise default address.
