Optimize template description and format template

diff --git a/documents/solution/internet-application-development/efficiently-build-app-on-the-cloud.yml b/documents/solution/internet-application-development/efficiently-build-app-on-the-cloud.yml
--- a/documents/solution/internet-application-development/efficiently-build-app-on-the-cloud.yml
+++ b/documents/solution/internet-application-development/efficiently-build-app-on-the-cloud.yml
@@ -179,45 +179,106 @@ Resources:
       Sync: true
       Timeout: 3600
       CommandContent:
-        Fn::Sub: "#!/bin/bash\n\n# 环境变量配置\nexport PATH=/usr/local/bin:$PATH\n\necho\
-          \ \"export APPLETS_RDS_ENDPOINT=${RdsInstance.InnerConnectionString}\" >>\
-          \ ~/.bashrc\necho \"export APPLETS_RDS_USER=${DBUserName}\" >> ~/.bashrc\n\
-          echo \"export APPLETS_RDS_PASSWORD=${DBPassword}\" >> ~/.bashrc\necho \"\
-          export APPLETS_RDS_DB_NAME=app\" >> ~/.bashrc\nsource ~/.bashrc\n\n# 网络检查地址\n\
-          NETWORK_CHECk_ADDR=\"help-static-aliyun-doc.aliyuncs.com\"\n\nfunction unsupported_system()\
-          \ {\n    log_fatal 1 \"Unsupported System: $1\"\n}\n\nfunction log_info()\
-          \ {\n    printf \"%s [INFO] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"\
-          $1\"\n}\n\nfunction log_error() {\n    printf \"%s [ERROR] %s\\n\" \"$(date\
-          \ '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n}\n\nfunction log_fatal() {\n    printf\
-          \ \"\\n========================================================================\\\
-          n\"\n    printf \"%s [FATAL] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"\
-          $2\"\n    printf \"\\n========================================================================\\\
-          n\"\n    exit $1\n}\n\nfunction debug_exec(){\n    local cmd=\"$@\"\n  \
-          \  log_info \"$cmd\"\n    eval \"$cmd\"\n    ret=$?\n    echo \"\"\n   \
-          \ log_info \"$cmd, exit code: $ret\"\n    return $ret\n}\n\nfunction check_network_available()\
-          \ {\n    log_info \"ping $NETWORK_CHECk_ADDR ...\"\n    if ! debug_exec\
-          \ ping -c 4 $NETWORK_CHECk_ADDR; then\n        log_fatal 2 \"Could not connect\
-          \ to https://$NETWORK_CHECk_ADDR\"\n    fi\n}\n\nfunction install_java()\
-          \ {\n    log_info \"install java\"\n    yum upgrade & yum install java-1.8.0-openjdk-devel\
-          \ -y\n}\n\nfunction init_database() {\n    log_info \"install mysql 1.20.1\"\
-          \n    yum install -y mysql\n    mysql -h $APPLETS_RDS_ENDPOINT -u $APPLETS_RDS_USER\
-          \ -p$APPLETS_RDS_PASSWORD < /data/script.sql\n}\n\nlog_info \"System Information:\"\
-          \nif ! lsb_release -a; then\n    unsupported_system\nfi;\necho \"\"\n\n\
-          check_network_available\n\nmkdir /data\ncat << \"EOF\" > /data/script.sql\n\
-          -- script.sql\nUSE app;\nCREATE TABLE `todo_list` (\n  `id` bigint NOT NULL\
-          \ COMMENT 'id',\n  `title` varchar(128) NOT NULL COMMENT 'title',\n  `desc`\
-          \ text NOT NULL COMMENT 'description',\n  `status` varchar(128) NOT NULL\
-          \ COMMENT 'status 未开始、进行中、已完成、已取消',\n  `priority` varchar(128) NOT NULL\
-          \ COMMENT 'priority 高、中、低',\n  `expect_time` datetime COMMENT 'expect time',\n\
-          \  `actual_completion_time` datetime COMMENT 'actual completion time',\n\
-          \  `gmt_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create\
-          \ time',\n  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT\
-          \ 'modified time',\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4\
-          \ COLLATE=utf8mb4_0900_ai_ci\n;\nINSERT INTO todo_list \n(id, title, `desc`,\
-          \ `status`, priority, expect_time)\nvalue(1,  \"创建一个小程序\", \"使用阿里云解决方案快速搭建一个App应用\"\
-          , \"进行中\", \"高\", \"2024-04-01 00:00:00\")\n\nEOF\n\nif ! debug_exec install_java;\
-          \ then\n    log_fatal 3 \"install java failed\"\nfi\n\nif ! debug_exec init_database;\
-          \ then\n    log_fatal 4 \"init database failed\"\nfi"
+        Fn::Sub: |-
+          #!/bin/bash
+          
+          # 环境变量配置
+          export PATH=/usr/local/bin:$PATH
+          
+          echo "export APPLETS_RDS_ENDPOINT=${RdsInstance.InnerConnectionString}" >> ~/.bashrc
+          echo "export APPLETS_RDS_USER=${DBUserName}" >> ~/.bashrc
+          echo "export APPLETS_RDS_PASSWORD=${DBPassword}" >> ~/.bashrc
+          echo "export APPLETS_RDS_DB_NAME=app" >> ~/.bashrc
+          source ~/.bashrc
+          
+          # 网络检查地址
+          NETWORK_CHECk_ADDR="help-static-aliyun-doc.aliyuncs.com"
+          
+          function unsupported_system() {
+              log_fatal 1 "Unsupported System: $1"
+          }
+          
+          function log_info() {
+              printf "%s [INFO] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+          
+          function log_error() {
+              printf "%s [ERROR] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+          
+          function log_fatal() {
+              printf "\n========================================================================\n"
+              printf "%s [FATAL] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$2"
+              printf "\n========================================================================\n"
+              exit $1
+          }
+          
+          function debug_exec(){
+              local cmd="$@"
+              log_info "$cmd"
+              eval "$cmd"
+              ret=$?
+              echo ""
+              log_info "$cmd, exit code: $ret"
+              return $ret
+          }
+
+          function check_network_available() {
+              log_info "ping $NETWORK_CHECk_ADDR ..."
+              if ! debug_exec ping -c 4 $NETWORK_CHECk_ADDR; then
+                  log_fatal 2 "Could not connect to https://$NETWORK_CHECk_ADDR"
+              fi
+          }
+          
+          function install_java() {
+              log_info "install java"
+              yum upgrade & yum install java-1.8.0-openjdk-devel -y
+          }
+          
+          function init_database() {
+              log_info "install mysql 1.20.1"
+              yum install -y mysql
+              mysql -h $APPLETS_RDS_ENDPOINT -u $APPLETS_RDS_USER -p$APPLETS_RDS_PASSWORD < /data/script.sql
+          }
+          
+          log_info "System Information:"
+          if ! lsb_release -a; then
+              unsupported_system
+          fi;
+          echo ""
+          
+          check_network_available
+          
+          mkdir /data
+          cat << "EOF" > /data/script.sql
+          -- script.sql
+          USE app;
+          CREATE TABLE `todo_list` (
+            `id` bigint NOT NULL COMMENT 'id',
+            `title` varchar(128) NOT NULL COMMENT 'title',
+            `desc` text NOT NULL COMMENT 'description',
+            `status` varchar(128) NOT NULL COMMENT 'status 未开始、进行中、已完成、已取消',
+            `priority` varchar(128) NOT NULL COMMENT 'priority 高、中、低',
+            `expect_time` datetime COMMENT 'expect time',
+            `actual_completion_time` datetime COMMENT 'actual completion time',
+            `gmt_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
+            `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'modified time',
+            PRIMARY KEY (`id`)
+          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
+          ;
+          INSERT INTO todo_list 
+          (id, title, `desc`, `status`, priority, expect_time)
+          value(1,  "创建一个小程序", "使用阿里云解决方案快速搭建一个App应用", "进行中", "高", "2024-04-01 00:00:00")
+          
+          EOF
+          
+          if ! debug_exec install_java; then
+              log_fatal 3 "install java failed"
+          fi
+          
+          if ! debug_exec init_database; then
+              log_fatal 4 "init database failed"
+          fi
   DomainRecord:
     Type: ALIYUN::DNS::DomainRecord
     Condition: DnsRecord
diff --git a/documents/solution/internet-application-development/file-processing-on-fc.yml b/documents/solution/internet-application-development/file-processing-on-fc.yml
--- a/documents/solution/internet-application-development/file-processing-on-fc.yml
+++ b/documents/solution/internet-application-development/file-processing-on-fc.yml
@@ -334,31 +334,70 @@ Resources:
       Type: RunShellScript
       Timeout: 300
       CommandContent:
-        Fn::Sub: "#!/bin/bash\n\ncat << EOF >> ~/.bashrc\nexport APPLETS_RDS_ENDPOINT=\"\
-          ${RdsInstance.InnerConnectionString}\"\nexport APPLETS_RDS_USER=\"${DBUserName}\"\
-          \nexport APPLETS_RDS_DB_NAME=\"applets\"\nexport APPLETS_RDS_PASSWORD=\"\
-          ${DBPassword}\"\nexport ALIYUN_RAM_ROLE_NAME=\"${FcDemoRole}\"\nexport ALIYUN_OSS_ENDPOINT=\"\
-          oss-${ALIYUN::Region}.aliyuncs.com\"\nexport ALIYUN_REGION_ID=\"${ALIYUN::Region}\"\
-          \nexport ALIYUN_OSS_BUCKET=\"${OssBucket}\"\nexport ECS_IP=`curl http://100.100.100.200/latest/meta-data/eipv4`\n\
-          export ALIYUN_MNS_ENDPOINT=\"http://${ALIYUN::TenantId}.mns.${ALIYUN::Region}-internal.aliyuncs.com\"\
-          \nexport ALIYUN_MNS_QUEUE=\"${BucketName}-oss-queue\"\nexport WANX_DEMO_USERNAME=\"\
-          ${DemoUserName}\"\nexport WANX_DEMO_PASSWORD=\"${DemoUserPassword}\"\n\n\
-          EOF\n\ncat << EOF > ~/.ossutilconfig\n[Credentials]\nendpoint = oss-${ALIYUN::Region}-internal.aliyuncs.com\n\
-          mode = EcsRamRole\necsRoleName = ${FcDemoRole}\n\nEOF\n\nfunction log_info()\
-          \ {\n    printf \"%s [INFO] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"\
-          $1\"\n}\n\nfunction log_error() {\n    printf \"%s [ERROR] %s\\n\" \"$(date\
-          \ '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n}\n\nfunction debug_exec(){\n    local\
-          \ cmd=\"$@\"\n    log_info \"$cmd\"\n    eval \"$cmd\"\n    ret=$?\n   \
-          \ echo \"\"\n    log_info \"$cmd, exit code: $ret\"\n    return $ret\n}\n\
-          \nfunction pre_work(){\n  source ~/.bashrc\n  yum upgrade & yum install\
-          \ -y java-1.8.0-openjdk-devel unzip zip\n  sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh\
-          \ | sudo bash\n  \n  wget -O fc-web-demo-job-jar-with-dependencies.jar https://help-static-aliyun-doc.aliyuncs.com/demos/fc-web-demo-job-jar-with-dependencies.jar\n\
-          \  zip fc-web-demo-job-jar-with-dependencies.jar.zip fc-web-demo-job-jar-with-dependencies.jar\n\
-          \  ossutil cp fc-web-demo-job-jar-with-dependencies.jar.zip oss://${OssBucket}/fc-code/\
-          \ -c ~/.ossutilconfig\n\n  wget -O demo.zip https://help-static-aliyun-doc.aliyuncs.com/demos/demo.zip\n\
-          \  unzip -d /home/admin demo.zip\n}\n\ndebug_exec pre_work\n\ncd /home/admin/\
-          \ \ndebug_exec \"nohup sh deploy.sh start fc-web-demo-0.0.1-SNAPSHOT.jar\
-          \ > deploy.log 2>&1 &\""
+        Fn::Sub: |-
+          #!/bin/bash
+
+          cat << EOF >> ~/.bashrc
+          export APPLETS_RDS_ENDPOINT="${RdsInstance.InnerConnectionString}"
+          export APPLETS_RDS_USER="${DBUserName}"
+          export APPLETS_RDS_DB_NAME="applets"
+          export APPLETS_RDS_PASSWORD="${DBPassword}"
+          export ALIYUN_RAM_ROLE_NAME="${FcDemoRole}"
+          export ALIYUN_OSS_ENDPOINT="oss-${ALIYUN::Region}.aliyuncs.com"
+          export ALIYUN_REGION_ID="${ALIYUN::Region}"
+          export ALIYUN_OSS_BUCKET="${OssBucket}"
+          export ECS_IP=`curl http://100.100.100.200/latest/meta-data/eipv4`
+          export ALIYUN_MNS_ENDPOINT="http://${ALIYUN::TenantId}.mns.${ALIYUN::Region}-internal.aliyuncs.com"
+          export ALIYUN_MNS_QUEUE="${BucketName}-oss-queue"
+          export WANX_DEMO_USERNAME="${DemoUserName}"
+          export WANX_DEMO_PASSWORD="${DemoUserPassword}"
+          
+          EOF
+          
+          cat << EOF > ~/.ossutilconfig
+          [Credentials]
+          endpoint = oss-${ALIYUN::Region}-internal.aliyuncs.com
+          mode = EcsRamRole
+          ecsRoleName = ${FcDemoRole}
+          
+          EOF
+          
+          function log_info() {
+              printf "%s [INFO] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+          
+          function log_error() {
+              printf "%s [ERROR] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+          
+          function debug_exec(){
+              local cmd="$@"
+              log_info "$cmd"
+              eval "$cmd"
+              ret=$?
+              echo ""
+              log_info "$cmd, exit code: $ret"
+              return $ret
+          }
+          
+          function pre_work(){
+            source ~/.bashrc
+            yum upgrade & yum install -y java-1.8.0-openjdk-devel unzip zip
+            sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
+            
+            wget -O fc-web-demo-job-jar-with-dependencies.jar https://help-static-aliyun-doc.aliyuncs.com/demos/fc-web-demo-job-jar-with-dependencies.jar
+            zip fc-web-demo-job-jar-with-dependencies.jar.zip fc-web-demo-job-jar-with-dependencies.jar
+            ossutil cp fc-web-demo-job-jar-with-dependencies.jar.zip oss://${OssBucket}/fc-code/ -c ~/.ossutilconfig
+
+            wget -O demo.zip https://help-static-aliyun-doc.aliyuncs.com/demos/demo.zip
+            unzip -d /home/admin demo.zip
+          }
+          
+          debug_exec pre_work
+          
+          cd /home/admin/ 
+          debug_exec "nohup sh deploy.sh start fc-web-demo-0.0.1-SNAPSHOT.jar > deploy.log 2>&1 &"
+  
   FcService:
     Type: ALIYUN::FC::Service
     Properties:
diff --git a/documents/solution/internet-application-development/rapidly-enterprise-portal.yml b/documents/solution/internet-application-development/rapidly-enterprise-portal.yml
--- a/documents/solution/internet-application-development/rapidly-enterprise-portal.yml
+++ b/documents/solution/internet-application-development/rapidly-enterprise-portal.yml
@@ -146,22 +146,61 @@ Resources:
       Sync: true
       Timeout: 3600
       CommandContent:
-        Fn::Sub: "#!/bin/bash\n\n# script exit code:\n# 0 - success\n# 1 - unsupported\
-          \ system\n# 2 - network not available\n# 3 - failed install java \n\n# 环境变量配置\n\
-          export PATH=/usr/local/bin:$PATH\n\nfunction unsupported_system() {\n  \
-          \  log_fatal 1 \"Unsupported System: $1\"\n}\n\nfunction log_info() {\n\
-          \    printf \"%s [INFO] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n\
-          }\n\nfunction log_error() {\n    printf \"%s [ERROR] %s\\n\" \"$(date '+%Y-%m-%d\
-          \ %H:%M:%S')\" \"$1\"\n}\n\nfunction log_fatal() {\n    printf \"\\n========================================================================\\\
-          n\"\n    printf \"%s [FATAL] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"\
-          $2\"\n    printf \"\\n========================================================================\\\
-          n\"\n    exit $1\n}\n\nfunction debug_exec(){\n    local cmd=\"$@\"\n  \
-          \  log_info \"$cmd\"\n    eval \"$cmd\"\n    ret=$?\n    echo \"\"\n   \
-          \ log_info \"$cmd, exit code: $ret\"\n    return $ret\n}\n\nfunction install_java()\
-          \ {\n    log_info \"install java\"\n    yum upgrade & yum install java-1.8.0-openjdk-devel\
-          \ -y\n}\n\nlog_info \"System Information:\"\nif ! lsb_release -a; then\n\
-          \    unsupported_system\nfi;\necho \"\"\n\nif ! debug_exec install_java;\
-          \ then\n    log_fatal 3 \"install java failed\"\nfi"
+        Fn::Sub: |-
+          #!/bin/bash
+
+          # script exit code:
+          # 0 - success
+          # 1 - unsupported system
+          # 2 - network not available
+          # 3 - failed install java 
+
+          # 环境变量配置
+          export PATH=/usr/local/bin:$PATH
+
+          function unsupported_system() {
+              log_fatal 1 "Unsupported System: $1"
+          }
+
+          function log_info() {
+              printf "%s [INFO] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+
+          function log_error() {
+              printf "%s [ERROR] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+
+          function log_fatal() {
+              printf "\n========================================================================\n"
+              printf "%s [FATAL] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$2"
+              printf "\n========================================================================\n"
+              exit $1
+          }
+
+          function debug_exec(){
+              local cmd="$@"
+              log_info "$cmd"
+              eval "$cmd"
+              ret=$?
+              echo ""
+              log_info "$cmd, exit code: $ret"
+              return $ret
+          }
+
+          function install_java() {
+              log_info "install java"
+              yum upgrade & yum install java-1.8.0-openjdk-devel -y
+          }
+
+          log_info "System Information:"
+          if ! lsb_release -a; then
+              unsupported_system
+          fi;
+          echo ""
+
+          if ! debug_exec install_java; then
+              log_fatal 3 "install java failed"
+          fi
   DomainRecord:
     Type: ALIYUN::DNS::DomainRecord
     Condition: DnsRecord
diff --git a/documents/solution/internet-application-development/websites-from-HTTP-to-HTTPS.yml b/documents/solution/internet-application-development/websites-from-HTTP-to-HTTPS.yml
--- a/documents/solution/internet-application-development/websites-from-HTTP-to-HTTPS.yml
+++ b/documents/solution/internet-application-development/websites-from-HTTP-to-HTTPS.yml
@@ -165,32 +165,82 @@ Resources:
       Sync: true
       Timeout: 3600
       CommandContent:
-        Fn::Sub: "#!/bin/bash\n\n# script exit code:\n# 0 - success\n# 1 - unsupported\
-          \ system\n# 2 - network not available\n# 3 - failed install nginx\n\n# 环境变量配置\n\
-          export PATH=/usr/local/bin:$PATH\n\n# 网络检查地址\nNETWORK_CHECk_ADDR=\"help-static-aliyun-doc.aliyuncs.com\"\
-          \n\nfunction unsupported_system() {\n    log_fatal 1 \"Unsupported System:\
-          \ $1\"\n}\n\nfunction log_info() {\n    printf \"%s [INFO] %s\\n\" \"$(date\
-          \ '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n}\n\nfunction log_error() {\n    printf\
-          \ \"%s [ERROR] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n}\n\nfunction\
-          \ log_fatal() {\n    printf \"\\n========================================================================\\\
-          n\"\n    printf \"%s [FATAL] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"\
-          $2\"\n    printf \"\\n========================================================================\\\
-          n\"\n    exit $1\n}\n\nfunction debug_exec(){\n    local cmd=\"$@\"\n  \
-          \  log_info \"$cmd\"\n    eval \"$cmd\"\n    ret=$?\n    echo \"\"\n   \
-          \ log_info \"$cmd, exit code: $ret\"\n    return $ret\n}\n\nfunction check_network_available()\
-          \ {\n    log_info \"ping $NETWORK_CHECk_ADDR ...\"\n    if ! debug_exec\
-          \ ping -c 4 $NETWORK_CHECk_ADDR; then\n        log_fatal 2 \"Could not connect\
-          \ to https://$NETWORK_CHECk_ADDR\"\n    fi\n}\n\nfunction set_ros_flag()\
-          \ {\n    log_info \"set ros flag to .ros.provision\"\n    echo \"$(date\
-          \ '+%Y-%m-%d %H:%M:%S') [${ALIYUN::StackId}] [${SolutionName}]\" >> .ros.provision\n\
-          }\n\nlog_info \"System Information:\"\nif ! lsb_release -a; then\n    unsupported_system\n\
-          fi;\necho \"\"\n\ncheck_network_available\nlog_info \"install nginx 1.20.1\"\
-          \nif ! debug_exec yum -y install nginx-1.20.1; then\n    log_fatal 3 \"\
-          install nginx failed\"\nfi\n\nlog_info \"download example\"\nwget -O /usr/share/nginx/html/index.html\
-          \ https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20231013/jhgg/index.html\n\
-          wget -O /usr/share/nginx/html/lipstick.png https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230925/zevs/lipstick.png\n\
-          \nlog_info \"start and enable nginx\"\nsystemctl start nginx \nsystemctl\
-          \ enable nginx\nset_ros_flag"
+        Fn::Sub: |-
+          #!/bin/bash
+          
+          # script exit code:
+          # 0 - success
+          # 1 - unsupported system
+          # 2 - network not available
+          # 3 - failed install nginx
+          
+          # 环境变量配置
+          export PATH=/usr/local/bin:$PATH
+          
+          # 网络检查地址
+          NETWORK_CHECk_ADDR="help-static-aliyun-doc.aliyuncs.com"
+          
+          function unsupported_system() {
+              log_fatal 1 "Unsupported System: $1"
+          }
+          
+          function log_info() {
+              printf "%s [INFO] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+          
+          function log_error() {
+              printf "%s [ERROR] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+          }
+          
+          function log_fatal() {
+              printf "\n========================================================================\n"
+              printf "%s [FATAL] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$2"
+              printf "\n========================================================================\n"
+              exit $1
+          }
+          
+          function debug_exec(){
+              local cmd="$@"
+              log_info "$cmd"
+              eval "$cmd"
+              ret=$?
+              echo ""
+              log_info "$cmd, exit code: $ret"
+              return $ret
+          }
+          
+          function check_network_available() {
+              log_info "ping $NETWORK_CHECk_ADDR ..."
+              if ! debug_exec ping -c 4 $NETWORK_CHECk_ADDR; then
+                  log_fatal 2 "Could not connect to https://$NETWORK_CHECk_ADDR"
+              fi
+          }
+          
+          function set_ros_flag() {
+              log_info "set ros flag to .ros.provision"
+              echo "$(date '+%Y-%m-%d %H:%M:%S') [${ALIYUN::StackId}] [${SolutionName}]" >> .ros.provision
+          }
+          
+          log_info "System Information:"
+          if ! lsb_release -a; then
+              unsupported_system
+          fi;
+          echo ""
+          
+          check_network_available
+          log_info "install nginx 1.20.1"
+          if ! debug_exec yum -y install nginx-1.20.1; then
+              log_fatal 3 "install nginx failed"
+          fi
+          
+          log_info "download example"
+          wget -O /usr/share/nginx/html/index.html https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20231013/jhgg/index.html
+          wget -O /usr/share/nginx/html/lipstick.png https://help-static-aliyun-doc.aliyuncs.com/file-manage-files/zh-CN/20230925/zevs/lipstick.png
+          
+          log_info "start and enable nginx"
+          systemctl start nginx 
+          systemctl enable nginx
+          set_ros_flag
   DomainRecord:
     Type: ALIYUN::DNS::DomainRecord
     Condition: DnsRecord
@@ -226,59 +276,122 @@ Resources:
       Timeout: 3600
       CommandContent:
         Fn::Sub:
-        - "#!/bin/bash\nfunction log_info() {\n    printf \"%s [INFO] %s\\n\" \"$(date\
-          \ '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n}\n\nfunction log_error() {\n    printf\
-          \ \"%s [ERROR] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"$1\"\n}\n\nfunction\
-          \ log_fatal() {\n    printf \"\\n========================================================================\\\
-          n\"\n    printf \"%s [FATAL] %s\\n\" \"$(date '+%Y-%m-%d %H:%M:%S')\" \"\
-          $2\"\n    printf \"\\n========================================================================\\\
-          n\"\n    exit $1\n}\n\nfunction debug_exec(){\n    local cmd=\"$@\"\n  \
-          \  log_info \"$cmd\"\n    eval \"$cmd\"\n    ret=$?\n    echo \"\"\n   \
-          \ log_info \"$cmd, exit code: $ret\"\n    return $ret\n}\n\nfunction check_ros_flag()\
-          \ {\n    log_info \"check ros flag in .ros.provision.\"\n    if [ ! -f .ros.provision\
-          \ ]; then\n        log_fatal 1 \".ros.provision file is not exist, instance\
-          \ not deployed nginx by ROS\"\n    else\n        name=`tail -n 1 .ros.provision\
-          \ | grep -oP '\\[.*?\\]\\s*\\K\\[.*?\\]' | tr -d '[]'`\n        if [ \"\
-          $name\" != \"${SolutionName}\" ]; then\n            log_fatal 2 \"solution\
-          \ name $name in .ros.provision is not ${SolutionName}.\"\n        fi\n \
-          \   fi\n}\n\nfunction download_and_check_cert_file() {\n    log_info \"\
-          down load and check zip file.\"\n    yum install -y unzip\n    mkdir /etc/nginx/cert\
-          \ && cd /etc/nginx/cert\n    if ! debug_exec \"wget -O cert.zip '${SSLCert}'\"\
-          ; then\n        log_fatal 3 \"cannot download cert form ${SSLCert}\"\n \
-          \   fi\n    \n    if ! debug_exec unzip cert.zip ; then\n        log_fatal\
-          \ 4 \"the uploaded file is not in zip format.\"\n    fi\n    PEM_FILE=`ls\
-          \ *.pem`\n    KEY_FILE=`ls *.key`\n\n    if [ -z \"$PEM_FILE\" ]; then\n\
-          \        log_fatal 5 \"there are no files ending in .pem in the uploaded\
-          \ zip file.\" \n    fi\n\n    if [ -z \"$KEY_FILE\" ]; then\n        log_fatal\
-          \ 5 \"there are no files ending in .key in the uploaded zip file.\" \n \
-          \   fi              \n}\n\ncheck_ros_flag\ndownload_and_check_cert_file\n\
-          \ncat << EOF > /etc/nginx/conf.d/ssl_demo.conf\nserver {\n    #HTTPS的默认访问端口443\n\
-          \    #如果未在此处配置HTTPS的默认访问端口，可能会造成Nginx无法启动。\n    listen 443 ssl;\n    #填写证书绑定的域名\n\
-          \    server_name ${DomainName};    \n    \n    #填写证书文件绝对路径\n    ssl_certificate\
-          \      \"/etc/nginx/cert/$PEM_FILE\";\n    #填写证书私钥文件绝对路径 \n    ssl_certificate_key\
-          \  \"/etc/nginx/cert/$KEY_FILE\";\n\n    ssl_session_cache    shared:SSL:1m;\n\
-          \    ssl_session_timeout  5m;\n\n    #默认加密套件\n    ssl_ciphers  HIGH:!aNULL:!MD5;\n\
-          \n    #自定义设置使用的TLS协议的类型以及加密套件（以下为配置示例，请您自行评估是否需要配置）\n    #TLS协议版本越高，HTTPS通信的安全性越高，但是相较于低版本TLS协议，高版本TLS协议对浏览器的兼容性较差。\n\
-          \    #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;\n\
-          \    #ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;\n\n    #表示优先使用服务端加密套件。默认开启\n\
-          \    ssl_prefer_server_ciphers  on;\n\n    location / {\n        root  \
-          \ html;\n        index  index.html index.htm;\n    }\n}\nEOF\n\nif ! debug_exec\
-          \ nginx -s reload ; then\n    log_fatal 6 \"reload nginx failed.\"\nfi\n"
-        - DomainName:
-            Fn::If:
-            - DomainPrefixIsNull
-            - Fn::GetJsonValue:
-              - DomainName
-              - Ref: DomainName
-            - Fn::Join:
-              - .
-              - - Fn::GetJsonValue:
-                  - DomainPrefix
-                  - Ref: DomainName
+          - |
+            #!/bin/bash
+            function log_info() {
+                printf "%s [INFO] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+            }
+            
+            function log_error() {
+                printf "%s [ERROR] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$1"
+            }
+            
+            function log_fatal() {
+                printf "\n========================================================================\n"
+                printf "%s [FATAL] %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$2"
+                printf "\n========================================================================\n"
+                exit $1
+            }
+            
+            function debug_exec(){
+                local cmd="$@"
+                log_info "$cmd"
+                eval "$cmd"
+                ret=$?
+                echo ""
+                log_info "$cmd, exit code: $ret"
+                return $ret
+            }
+            
+            function check_ros_flag() {
+                log_info "check ros flag in .ros.provision."
+                if [ ! -f .ros.provision ]; then
+                    log_fatal 1 ".ros.provision file is not exist, instance not deployed nginx by ROS"
+                else
+                    name=`tail -n 1 .ros.provision | grep -oP '\[.*?\]\s*\K\[.*?\]' | tr -d '[]'`
+                    if [ "$name" != "${SolutionName}" ]; then
+                        log_fatal 2 "solution name $name in .ros.provision is not ${SolutionName}."
+                    fi
+                fi
+            }
+            
+            function download_and_check_cert_file() {
+                log_info "down load and check zip file."
+                yum install -y unzip
+                mkdir /etc/nginx/cert && cd /etc/nginx/cert
+                if ! debug_exec "wget -O cert.zip '${SSLCert}'"; then
+                    log_fatal 3 "cannot download cert form ${SSLCert}"
+                fi
+                
+                if ! debug_exec unzip cert.zip ; then
+                    log_fatal 4 "the uploaded file is not in zip format."
+                fi
+                PEM_FILE=`ls *.pem`
+                KEY_FILE=`ls *.key`
+            
+                if [ -z "$PEM_FILE" ]; then
+                    log_fatal 5 "there are no files ending in .pem in the uploaded zip file." 
+                fi
+  
+                if [ -z "$KEY_FILE" ]; then
+                    log_fatal 5 "there are no files ending in .key in the uploaded zip file." 
+                fi              
+            }
+            
+            check_ros_flag
+            download_and_check_cert_file
+            
+            cat << EOF > /etc/nginx/conf.d/ssl_demo.conf
+            server {
+                #HTTPS的默认访问端口443
+                #如果未在此处配置HTTPS的默认访问端口，可能会造成Nginx无法启动。
+                listen 443 ssl;
+                #填写证书绑定的域名
+                server_name ${DomainName};    
+                
+                #填写证书文件绝对路径
+                ssl_certificate      "/etc/nginx/cert/$PEM_FILE";
+                #填写证书私钥文件绝对路径 
+                ssl_certificate_key  "/etc/nginx/cert/$KEY_FILE";
+         
+                ssl_session_cache    shared:SSL:1m;
+                ssl_session_timeout  5m;
+            
+                #默认加密套件
+                ssl_ciphers  HIGH:!aNULL:!MD5;
+            
+                #自定义设置使用的TLS协议的类型以及加密套件（以下为配置示例，请您自行评估是否需要配置）
+                #TLS协议版本越高，HTTPS通信的安全性越高，但是相较于低版本TLS协议，高版本TLS协议对浏览器的兼容性较差。
+                #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
+                #ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
+            
+                #表示优先使用服务端加密套件。默认开启
+                ssl_prefer_server_ciphers  on;
+         
+                location / {
+                    root   html;
+                    index  index.html index.htm;
+                }
+            }
+            EOF
+            
+            if ! debug_exec nginx -s reload ; then
+                log_fatal 6 "reload nginx failed."
+            fi
+          - DomainName:
+              Fn::If:
+                - DomainPrefixIsNull
                 - Fn::GetJsonValue:
-                  - DomainName
-                  - Ref: DomainName
-    DependsOn: InstallNginx
+                    - DomainName
+                    - Ref: DomainName
+                - Fn::Join:
+                    - '.'
+                    - - Fn::GetJsonValue:
+                          - DomainPrefix
+                          - Ref: DomainName
+                      - Fn::GetJsonValue:
+                          - DomainName
+                          - Ref: DomainName
 Outputs:
   WebUrl:
     Description:
diff --git a/examples/ai/ecs-instance-flowise.yml b/examples/ai/ecs-instance-flowise.yml
--- a/examples/ai/ecs-instance-flowise.yml
+++ b/examples/ai/ecs-instance-flowise.yml
@@ -126,19 +126,37 @@ Resources:
       Type: RunShellScript
       Sync: true
       Timeout: 1800
-      CommandContent: "#!/bin/bash\necho \"#########################\"\necho \"# Install\
-        \ NodeJS\"\necho \"#########################\"\ngit clone https://github.com/nvm-sh/nvm.git\
-        \ /opt/nvm && cd /opt/nvm\nret_code=$?\nif [ $ret_code -ne 0 ]; then\n  echo\
-        \ \"Git clone https://github.com/nvm-sh/nvm.git failed. Exiting.\"\n  exit\
-        \ $ret_code\nfi\n./install.sh\nexport NVM_DIR=\"$HOME/.nvm\"\n[ -s \"$NVM_DIR/nvm.sh\"\
-        \ ] && \\. \"$NVM_DIR/nvm.sh\"\n[ -s \"$NVM_DIR/bash_completion\" ] && \\\
-        . \"$NVM_DIR/bash_completion\"\nnvm install 22\nnpm config set registry https://registry.npmmirror.com\n\
-        npm i -g pnpm\n\necho \"#########################\"\necho \"# Install Flowise\"\
-        \necho \"#########################\"\ngit clone --depth 1 https://github.com/FlowiseAI/Flowise.git\
-        \ /opt/Flowise && cd /opt/Flowise\nret_code=$?\nif [ $ret_code -ne 0 ]; then\n\
-        \  echo \"Git clone https://github.com/FlowiseAI/Flowise.git failed. Exiting.\"\
-        \n  exit $ret_code\nfi\npnpm install\npnpm build\nnohup pnpm start > flowise.log\
-        \ 2>&1 &\n"
+      CommandContent: |
+        #!/bin/bash
+        echo "#########################"
+        echo "# Install NodeJS"
+        echo "#########################"
+        git clone https://github.com/nvm-sh/nvm.git /opt/nvm && cd /opt/nvm
+        ret_code=$?
+        if [ $ret_code -ne 0 ]; then
+          echo "Git clone https://github.com/nvm-sh/nvm.git failed. Exiting."
+          exit $ret_code
+        fi
+        ./install.sh
+        export NVM_DIR="$HOME/.nvm"
+        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
+        nvm install 22
+        npm config set registry https://registry.npmmirror.com
+        npm i -g pnpm
+        
+        echo "#########################"
+        echo "# Install Flowise"
+        echo "#########################"
+        git clone --depth 1 https://github.com/FlowiseAI/Flowise.git /opt/Flowise && cd /opt/Flowise
+        ret_code=$?
+        if [ $ret_code -ne 0 ]; then
+          echo "Git clone https://github.com/FlowiseAI/Flowise.git failed. Exiting."
+          exit $ret_code
+        fi
+        pnpm install
+        pnpm build
+        nohup pnpm start > flowise.log 2>&1 &
 Outputs:
   FlowiseUrl:
     Description: Flowise default address.
diff --git a/examples/isv/custom-image-ecs-datadisk.yml b/examples/isv/custom-image-ecs-datadisk.yml
--- a/examples/isv/custom-image-ecs-datadisk.yml
+++ b/examples/isv/custom-image-ecs-datadisk.yml
@@ -328,23 +328,51 @@ Resources:
         - InstanceIds
       CommandContent:
         Fn::Sub:
-        - "#!/bin/bash\n# 1. 如果使用了数据盘，需要对数据盘进行格式化，并挂载到指定目录，这里假定挂载到/data\ninit_and_mount_data_disk()\
-          \ {\n  local fs_type=$1\n  local mount_point=$2\n\n  # 找出磁盘设备（排除分区）\n  devices=(`lsblk\
-          \ -o NAME,FSTYPE --noheadings --nodeps | awk '$2 == \"\" {print $1}'`)\n\
-          \  # 找出不存在文件系统的磁盘设备\n  for device in ${!devices[@]};\n  do\n    lsblk -o\
-          \ NAME,FSTYPE --noheadings  | awk '$2 != \"\" {print $1}' | grep ${!device}\n\
-          \    if [[ $? -eq 1 ]]; then\n      data_disk=${!device}\n      break\n\
-          \    fi\n  done\n\n  # 为数据盘创建文件系统\n  mkfs -t ${!fs_type} /dev/${!data_disk}\n\
-          \n  cp /etc/fstab /etc/fstab.bak\n  mkdir ${!mount_point}\n  # 更新/etc/fstab并挂载磁盘\n\
-          \  echo `blkid /dev/${!data_disk} | awk '{print $2}' | sed 's/\\\\\\\"//g'`\
-          \ ${!mount_point} ext4 defaults 0 0 >> /etc/fstab\n  mount -a\n}\n\n# 挂盘到/data\n\
-          init_and_mount_data_disk ext4 /data\n\n# 2. 安装软件，或者对软件进行初始化配置，比如将数据文件目录指定到数据盘目录\n\
-          # yum install -y nginx\n\n# 3. 如果需要开机自启动，请添加系统服务并启用\n# systemctl enable\
-          \ nginx.service\n\n# 4. 配置启动脚本或者启动系统服务\n# systemctl start nginx.service\n\
-          \n# 5. 执行成功回调WaitCondition结束waitCondition的等待\n${CurlCli} -d \"{\\\"Data\\\
-          \" : \\\"Success\\\", \\\"status\\\" : \\\"SUCCESS\\\"}\"\n# 脚本里任何地方如果发现执行失败，使用以下命令返回FAILURE和错误信息\n\
-          # ${CurlCli} -d \"{\\\"Data\\\" : \\\"error message\\\", \\\"status\\\"\
-          \ : \\\"FAILURE\\\"}\"\n"
+        - |
+          #!/bin/bash
+          # 1. 如果使用了数据盘，需要对数据盘进行格式化，并挂载到指定目录，这里假定挂载到/data
+          init_and_mount_data_disk() {
+            local fs_type=$1
+            local mount_point=$2
+
+            # 找出磁盘设备（排除分区）
+            devices=(`lsblk -o NAME,FSTYPE --noheadings --nodeps | awk '$2 == "" {print $1}'`)
+            # 找出不存在文件系统的磁盘设备
+            for device in ${!devices[@]};
+            do
+              lsblk -o NAME,FSTYPE --noheadings  | awk '$2 != "" {print $1}' | grep ${!device}
+              if [[ $? -eq 1 ]]; then
+                data_disk=${!device}
+                break
+              fi
+            done
+
+            # 为数据盘创建文件系统
+            mkfs -t ${!fs_type} /dev/${!data_disk}
+
+            cp /etc/fstab /etc/fstab.bak
+            mkdir ${!mount_point}
+            # 更新/etc/fstab并挂载磁盘
+            echo `blkid /dev/${!data_disk} | awk '{print $2}' | sed 's/\\\"//g'` ${!mount_point} ext4 defaults 0 0 >> /etc/fstab
+            mount -a
+          }
+
+          # 挂盘到/data
+          init_and_mount_data_disk ext4 /data
+
+          # 2. 安装软件，或者对软件进行初始化配置，比如将数据文件目录指定到数据盘目录
+          # yum install -y nginx
+
+          # 3. 如果需要开机自启动，请添加系统服务并启用
+          # systemctl enable nginx.service
+
+          # 4. 配置启动脚本或者启动系统服务
+          # systemctl start nginx.service
+
+          # 5. 执行成功回调WaitCondition结束waitCondition的等待
+          ${CurlCli} -d "{\"Data\" : \"Success\", \"status\" : \"SUCCESS\"}"
+          # 脚本里任何地方如果发现执行失败，使用以下命令返回FAILURE和错误信息
+          # ${CurlCli} -d "{\"Data\" : \"error message\", \"status\" : \"FAILURE\"}"
         - CurlCli:
             Fn::GetAtt:
             - WaitConditionHandle
